import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {execFileSync,spawn} from "node:child_process";
import {ControllerLease,ControllerCasError,CONTROLLER_REF,type ControllerLeaseRecord} from "../src/controller-lease.js";
import type {FactoryInstance} from "../src/instance.js";
import {Store} from "../src/storage.js";

const git=(args:string[],cwd?:string)=>execFileSync("git",args,{cwd,encoding:"utf8"}).trim();
const repository={id:42,nodeId:"R_42",fullName:"owner/demo",defaultBranch:"main"},instance:FactoryInstance={schemaVersion:1,instanceId:"11111111-1111-4111-8111-111111111111",displayName:"Factory 111111",createdAt:"2026-09-21T00:00:00.000Z"};
const valid=(overrides:Partial<ControllerLeaseRecord>={}):ControllerLeaseRecord=>({schemaVersion:1,repositoryId:42,repositoryNodeId:"R_42",instanceId:"22222222-2222-4222-8222-222222222222",displayName:"Factory 222222",contact:"",generation:3,engineVersion:"0.3.0",acquiredAt:"2026-09-21T00:00:00.000Z",heartbeatAt:"2026-09-21T00:05:00.000Z",activeWorkCount:2,...overrides});
const identity=(digit:string):FactoryInstance=>({schemaVersion:1,instanceId:`${digit.repeat(8)}-${digit.repeat(4)}-4${digit.repeat(3)}-8${digit.repeat(3)}-${digit.repeat(12)}`,displayName:`Factory ${digit.repeat(6)}`,createdAt:"2026-09-21T00:00:00.000Z"});
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"factory-controller-")),remote=path.join(root,"origin.git"),writer=path.join(root,"writer"),home=path.join(root,"home");git(["init","--bare",remote]);git(["init",writer]);git(["config","user.name","Test"],writer);git(["config","user.email","test@example.com"],writer);git(["remote","add","origin",remote],writer);return{root,remote,writer,home,write(value:unknown){fs.writeFileSync(path.join(writer,"lease.json"),typeof value==="string"?value:JSON.stringify(value));git(["add","lease.json"],writer);git(["commit","-m","lease"],writer);const sha=git(["rev-parse","HEAD"],writer);git(["push","origin",`${sha}:${CONTROLLER_REF}`,`--force-with-lease=${CONTROLLER_REF}:`],writer);return sha;}};}

test("controller read reports absent and validates a current local-bare lease",()=>{const f=fixture();try{const client=new ControllerLease(repository,undefined,{home:f.home,remote:f.remote,instance,now:()=>Date.parse("2026-09-21T00:06:00.000Z")});assert.equal(client.readLease().state,"absent");const sha=f.write(valid()),observed=client.readLease();if(observed.state==="absent")throw new Error("expected lease");assert.equal(observed.state,"standby");assert.equal(observed.sha,sha);assert.equal(observed.record.activeWorkCount,2);assert.equal(observed.expiresAt,"2026-09-21T00:15:00.000Z");}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test("controller read rejects malformed and mismatched records",()=>{for(const [name,value,pattern] of [["malformed","not json",/Malformed controller lease/],["repository mismatch",valid({repositoryId:99}),/different GitHub repository identity/]] as const){const f=fixture();try{f.write(value);const client=new ControllerLease(repository,undefined,{home:f.home,remote:f.remote,instance});assert.throws(()=>client.readLease(),pattern,name);}finally{fs.rmSync(f.root,{recursive:true,force:true});}}});

test("two isolated homes racing on an absent ref produce one active and one standby",async()=>{const f=fixture();try{const source=path.resolve(new URL("../src/controller-lease.ts",import.meta.url).pathname),script=`import {ControllerLease} from ${JSON.stringify(source)};const [home,remote,digit]=process.argv.slice(1),id={schemaVersion:1,instanceId:digit.repeat(8)+'-'+digit.repeat(4)+'-4'+digit.repeat(3)+'-8'+digit.repeat(3)+'-'+digit.repeat(12),displayName:'Factory '+digit.repeat(6),createdAt:'now'},repo={id:42,nodeId:'R_42',fullName:'owner/demo',defaultBranch:'main'};console.log(new ControllerLease(repo,undefined,{home,remote,instance:id}).acquire().state);`,run=(home:string,digit:string)=>new Promise<string>((resolve,reject)=>{const child=spawn(process.execPath,["--import","tsx","--input-type=module","-e",script,home,f.remote,digit],{cwd:path.resolve(new URL("..",import.meta.url).pathname),stdio:["ignore","pipe","pipe"]});let out="",err="";child.stdout.on("data",chunk=>out+=chunk);child.stderr.on("data",chunk=>err+=chunk);child.on("close",code=>code===0?resolve(out.trim()):reject(new Error(err)));});const results=await Promise.all([run(path.join(f.root,"one"),"1"),run(path.join(f.root,"two"),"2")]);assert.deepEqual(results.sort(),["active","standby"]);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test("renewal requires the exact observed sha and same-instance reclaim keeps generation",()=>{const f=fixture();try{let now=Date.parse("2026-09-21T00:00:00.000Z");const owner=new ControllerLease(repository,undefined,{home:path.join(f.root,"owner"),remote:f.remote,instance:identity("1"),now:()=>now}),acquired=owner.acquire();if(acquired.state==="absent")throw new Error("missing lease");now+=1_000;const renewed=owner.renew(acquired);assert.equal(renewed.state,"active");assert.throws(()=>owner.renew(acquired),ControllerCasError);now+=700_000;const reclaimed=owner.acquire();if(reclaimed.state==="absent")throw new Error("missing lease");assert.equal(reclaimed.record.generation,1);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test("expired and forced takeovers increment generation and only one stale contender wins",()=>{const f=fixture();try{let now=Date.parse("2026-09-21T00:00:00.000Z");const owner=new ControllerLease(repository,undefined,{home:path.join(f.root,"owner"),remote:f.remote,instance:identity("1"),now:()=>now});owner.acquire();const early=new ControllerLease(repository,undefined,{home:path.join(f.root,"early"),remote:f.remote,instance:identity("2"),now:()=>now});assert.throws(()=>early.takeover(),/has not expired/);const forced=early.takeover(true);if(forced.state==="absent")throw new Error("missing lease");assert.equal(forced.record.generation,2);now+=700_000;const contenderA=new ControllerLease(repository,undefined,{home:path.join(f.root,"a"),remote:f.remote,instance:identity("3"),now:()=>now}),contenderB=new ControllerLease(repository,undefined,{home:path.join(f.root,"b"),remote:f.remote,instance:identity("4"),now:()=>now}),shownA=contenderA.readLease(),shownB=contenderB.readLease(),winner=contenderA.takeover(false,shownA);if(winner.state==="absent")throw new Error("missing lease");assert.equal(winner.record.generation,3);assert.throws(()=>contenderB.takeover(false,shownB),ControllerCasError);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});

test("release refuses unsafe work unless forced and deletes the ref with CAS",()=>{const f=fixture(),store=new Store(":memory:");try{const owner=new ControllerLease(repository,store,{home:path.join(f.root,"owner"),remote:f.remote,instance:identity("1")});owner.acquire();store.db.prepare("INSERT INTO work_items(id,issue_number,repo,created_at,updated_at,context,stage,status) VALUES('w',1,'owner/demo','now','now','{}','DESIGN','PAUSED')").run();assert.throws(()=>owner.release(),/active work item/);assert.equal(owner.release(true).state,"absent");assert.equal(git(["ls-remote",f.remote,CONTROLLER_REF]),"");}finally{store.db.close();fs.rmSync(f.root,{recursive:true,force:true});}});

test("all controller ref writes use the single explicit compare-and-swap function",()=>{const root=path.resolve(new URL("..",import.meta.url).pathname),files=[...walk(path.join(root,"src")),...walk(path.join(root,"scripts"))],matches=files.flatMap(file=>fs.readFileSync(file,"utf8").split("\n").filter(line=>line.includes("--force-with-lease" )).map(line=>({file,line})));assert.equal(matches.length,1,JSON.stringify(matches,null,2));assert.match(matches[0].line,/CONTROLLER_REF}:\$\{expected}/);for(const file of files){const source=fs.readFileSync(file,"utf8");assert.doesNotMatch(source,/push[^\n]{0,200}["']--force["']/i,file);}});
function walk(directory:string):string[]{return fs.readdirSync(directory,{withFileTypes:true}).flatMap(entry=>entry.isDirectory()?walk(path.join(directory,entry.name)):entry.isFile()&&/\.(?:ts|js|mjs|sh)$/.test(entry.name)?[path.join(directory,entry.name)]:[]);}
