import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../dashboard/app.js',import.meta.url),'utf8');
test('every inline dashboard action is exported by the module',()=>{const actions=[...source.matchAll(/onclick="([A-Za-z_$][\w$]*)\(/g)].map(match=>match[1]);assert.ok(actions.includes('sendWorkflowMessage'));for(const action of new Set(actions))assert.match(source,new RegExp(`window\\.${action}\\s*=`),`${action} must be available to inline onclick handlers`);});
test('setup mode leaves the URL once readiness has no missing requirements',()=>{assert.match(source,/if\(typeof setupMode!=="undefined"&&setupMode&&!data\.readiness\?\.missing\?\.length\)\{setupMode=false;history\.replaceState\(\{\},'',location\.pathname\)\}/);assert.doesNotMatch(source,/setupMode&&!field\.setup\?'advanced'/);});
test('settings progress stays beside the save button and exposes busy and completion states',()=>{
 const elements=new Map<string,any>();const context=vm.createContext({$:(key:string)=>{if(!elements.has(key))elements.set(key,{dataset:{},setAttribute(name:string,value:string){this[name]=value;}});return elements.get(key)}});
 vm.runInContext(source.split('\n').find(line=>line.startsWith('function settingsProgress('))!,context);
 vm.runInContext("settingsProgress('Validating…')",context);assert.equal(elements.get('#settings-save').textContent,'Applying…');assert.equal(elements.get('#settings-form')['aria-busy'],'true');
 vm.runInContext("settingsProgress('Saved.','success')",context);assert.equal(elements.get('#settings-progress').textContent,'Saved.');assert.equal(elements.get('#settings-progress').dataset.state,'success');assert.equal(elements.get('#settings-form')['aria-busy'],'false');
 vm.runInContext("settingsProgress('Could not save.','error')",context);assert.equal(elements.get('#settings-progress').dataset.state,'error');
});
test('Codex credentials include a visible provider name',()=>{
 const context=vm.createContext({escapeHtml:String,brandIcon:()=>'<img>',brandTitle:{codex:'Codex'},credentialBusy:false});
 for(const prefix of ['const brandLabel=','function credentialCards('])vm.runInContext(source.split('\n').find(line=>line.startsWith(prefix))!,context);
 const html=vm.runInContext("credentialCards({credentials:[{id:'codex',label:'Codex',status:'connected',installed:true,description:'Agents'}]})",context);
 assert.match(html,/<span>Codex<\/span>/);
});
test('Connections keeps Save and apply visible and configures Slack through its connection dialog',()=>{
 assert.doesNotMatch(source,/\$\('#settings-actions'\)\.hidden=id===['"]connections['"]/);
 const context=vm.createContext({escapeHtml:String,brandLabel:()=>'<span>Slack</span>',slackBusy:false,slackData:{configured:true,pending:2,failed:1,sent:3,lastError:'Webhook rejected'}});
 vm.runInContext(source.split('\n').find(line=>line.startsWith('function slackWebhookCard('))!,context);
 const html=vm.runInContext("slackWebhookCard()",context);
 assert.match(html,/Manage/);assert.match(html,/openSlackSettings\(\)/);assert.doesNotMatch(html,/data-setting="SLACK_WEBHOOK_URL"/);assert.doesNotMatch(html,/Send test/);
 const markup=fs.readFileSync(new URL('../dashboard/index.html',import.meta.url),'utf8');assert.match(markup,/id="slack-dialog"/);assert.match(markup,/id="slack-test"/);assert.match(source,/Last delivery error:/);
});
test('prompt viewer defaults to readable content and offers the exact agent JSON',()=>{
 const context=vm.createContext({escapeHtml:(value:string)=>String(value).replaceAll('<','&lt;')});for(const name of ['promptReadableHtml','promptAgentJson'])vm.runInContext(source.split('\n').find(line=>line.startsWith(`function ${name}(`))!,context);
 const readable=vm.runInContext("promptReadableHtml('# Goal\\n\\n- **First** `value`\\n- <unsafe>\\n\\nAC-1\\n\\n**Given** input')",context);assert.match(readable,/<h2>Goal<\/h2>/);assert.match(readable,/<ul><li><strong>First<\/strong> <code>value<\/code><\/li><li>&lt;unsafe><\/li><\/ul>/);assert.match(readable,/<h3 class="acceptance-criterion">AC-1<\/h3>/);assert.match(readable,/<strong>Given<\/strong> input/);assert.doesNotMatch(readable,/<unsafe>/);
 const json=vm.runInContext("promptAgentJson({id:'run-1',prompt:'# Goal',truncated:false})",context);assert.deepEqual(JSON.parse(json),{executionId:'run-1',instructions:'# Goal',truncated:false});assert.match(source,/selectPromptView\(dialog,'human'\)/);assert.match(source,/Human readable/);assert.match(source,/Agent JSON/);
});
test('human-readable markdown tables render across prompts, results and guidance',()=>{
 const context=vm.createContext({escapeHtml:(value:string)=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')});vm.runInContext(source.split('\n').find(line=>line.startsWith('function promptReadableHtml('))!,context);
 const markdown='| Restricción | Origen |\n| --- | --- |\n| Paleta **Openxpand** | `src/styles/global.css` |\n| Texto con \\| literal | <unsafe> |';
 const html=vm.runInContext('promptReadableHtml(input)',Object.assign(context,{input:markdown}));
 assert.match(html,/<div class="markdown-table-wrap"><table><thead><tr><th scope="col">Restricción<\/th><th scope="col">Origen<\/th><\/tr><\/thead>/);
 assert.match(html,/<strong>Openxpand<\/strong>/);assert.match(html,/<code>src\/styles\/global.css<\/code>/);assert.match(html,/Texto con \| literal/);assert.match(html,/&lt;unsafe&gt;/);assert.doesNotMatch(html,/<unsafe>/);
 assert.equal((html.match(/<tr>/g)||[]).length,3);
 const fenced=vm.runInContext('promptReadableHtml(input)',Object.assign(context,{input:'```md\n'+markdown+'\n```'}));assert.doesNotMatch(fenced,/<table>/);
});
test('failed issue details render a human-readable diagnosis and next action',()=>{
 const context=vm.createContext({escapeHtml:String,relative:()=>"now"});vm.runInContext(source.split('\n').find(line=>line.startsWith('function promptReadableHtml('))!,context);vm.runInContext(source.split('\n').find(line=>line.startsWith('function workDetails('))!,context);
 const html=vm.runInContext("workDetails({id:'w',activity:{label:'Failed',detail:'raw',diagnosis:{summary:'**Required** browser unavailable',evidence:'Use `Browser`',nextAction:'Restore it and retry'}}},new Set(['w']))",context);
 assert.match(html,/Failure diagnosis/);assert.match(html,/What happened/);assert.match(html,/<strong>Required<\/strong> browser unavailable/);assert.match(html,/What the system observed/);assert.match(html,/<code>Browser<\/code>/);assert.match(html,/What to do next/);assert.match(html,/Restore it and retry/);assert.doesNotMatch(html,/>raw</);
});
test('workflow composer appears before the newest-first conversation',()=>{
 const start=source.indexOf('function renderWorkflowThread('),end=source.indexOf('\nasync function loadWorkflowThread',start),render=source.slice(start,end);
 assert.ok(render.indexOf('<form class="thread-composer"')<render.indexOf('<div class="workflow-thread">'));
});
test('workflow messages refresh the open thread after the daemon applies them',()=>{
 assert.match(source,/threadRevisions/);assert.match(source,/await loadWorkflowThread\(id,true\)/);assert.match(source,/if\(panel\?\.open\)loadWorkflowThread\(id,true\)/);
});
test('workflow refresh preserves the open prompt and the draft',()=>{
 let html='',rendered=false;const input:any={value:'',addEventListener(){}},thread:any={scrollTop:0},turn:any={open:true,dataset:{threadTurn:'w:1'},addEventListener(){}};const root:any={get innerHTML(){return html},set innerHTML(value){html=value;rendered=true},querySelector(selector:string){if(!rendered)return null;if(selector==='[data-thread-message]')return input;if(selector==='.workflow-thread')return thread;return null},querySelectorAll(selector:string){return rendered&&selector==='[data-thread-turn]'?[turn]:[]}};
 const context=vm.createContext({applyQueueAvailability(){},document:{querySelector:()=>root},CSS:{escape:String},escapeHtml:String,relative:()=> '1m ago',roleName:()=> 'Architect',statusName:String,stateClass:()=>'',actionLabel:{retry:'Retry with guidance'},brandIcon:(provider:string)=>`<img data-provider="${provider}">`,brandTitle:{codex:'Codex',claude:'Claude'},sendWorkflowMessage(){},threadDrafts:new Map([['w','keep this guidance']]),expandedThreadTurns:new Set(['w:1']),collapsedThreadTurns:new Set(),latestThreadTurns:new Map(),threadResultViews:new Map(),threadResultContent:new Map()});vm.runInContext(source.split('\n').find(line=>line.startsWith('function promptReadableHtml('))!,context);const start=source.indexOf('function renderWorkflowThread('),end=source.indexOf('\nasync function loadWorkflowThread',start);vm.runInContext(source.slice(start,end),context);context.data={operator:{approver:true},actions:['retry'],turns:[{id:1,kind:'execution',role:'product-architect',provider:'codex',model:'auto',available:true,executionId:'run',manifest:{sections:{Issue:20}},outcome:'questions',status:'succeeded',startedAt:'2026-09-22T17:29:00.000Z',durationMs:102000,markdown:'# Architect questions',result:{outcome:'questions',summary:'Need input'}},{id:3,kind:'event',stage:'DESIGN',status:'FAILED',reason:'Design stopped',diagnosis:{summary:'Repeated summary',nextAction:'Repeated action'}},{id:4,kind:'human',login:'owner',command:'answer',source:'dashboard',text:'1. First answer\n2. Second answer\n\n- Keep this detail'}]};vm.runInContext("renderWorkflowThread('w',data)",context);assert.match(html,/data-thread-turn="w:1"[^>]* open/);assert.match(html,/data-thread-turn="w:4" open/);assert.doesNotMatch(html,/data-thread-turn="w:[23]"[^>]* open/);assert.ok(html.indexOf('@owner')<html.indexOf('DESIGN needs attention'));assert.ok(html.indexOf('DESIGN needs attention')<html.indexOf('Architect · questions'));assert.doesNotMatch(html,/Design stopped/);assert.match(html,/Agent execution/);assert.match(html,/Agent input/);assert.match(html,/Architect · questions/);assert.match(html,/1m 42s/);assert.match(html,/Reveal full prompt/);assert.match(html,/class="thread-agent"/);assert.match(html,/data-provider="codex"/);assert.match(html,/title="Codex"/);assert.match(html,/Auto \(provider recommended\)/);assert.match(html,/Human readable/);assert.match(html,/Agent JSON/);assert.match(html,/data-result-human ><h2>Architect questions<\/h2>/);assert.match(html,/data-result-json hidden/);assert.match(html,/"outcome": "questions"/);assert.match(html,/See the failure diagnosis above/);assert.doesNotMatch(html,/Repeated summary|Repeated action/);assert.match(html,/thread-human-body"><ol><li>First answer<\/li><li>Second answer<\/li><\/ol><ul><li>Keep this detail<\/li><\/ul>/);assert.equal(input.value,'keep this guidance');const before=html;vm.runInContext("renderWorkflowThread('w',data)",context);assert.equal(html,before);assert.equal(input.value,'keep this guidance');
});
test('new failure events stay collapsed when their diagnosis is already visible above',()=>{
 let html='',rendered=false;const root:any={get innerHTML(){return html},set innerHTML(value){html=value;rendered=true},querySelector(){return rendered?null:null},querySelectorAll(){return []}};
 const context=vm.createContext({applyQueueAvailability(){},document:{querySelector:()=>root},CSS:{escape:String},escapeHtml:String,relative:()=> '1m ago',roleName:String,statusName:String,stateClass:()=>'',actionLabel:{},threadDrafts:new Map(),expandedThreadTurns:new Set(),collapsedThreadTurns:new Set(),latestThreadTurns:new Map(),threadResultViews:new Map(),threadResultContent:new Map()});vm.runInContext(source.split('\n').find(line=>line.startsWith('function promptReadableHtml('))!,context);const start=source.indexOf('function renderWorkflowThread('),end=source.indexOf('\nasync function loadWorkflowThread',start);vm.runInContext(source.slice(start,end),context);
 context.data={operator:{approver:true},actions:[],turns:[{id:1,kind:'event',stage:'BUILD',status:'FAILED',reason:'Build failed',diagnosis:{summary:'A capability was unavailable'}}]};vm.runInContext("renderWorkflowThread('w',data)",context);assert.doesNotMatch(html,/data-thread-turn="w:1" open/);
});

test('the milestones filter hides intermediate turns, keeps the newest milestone open and stays off by default',()=>{
 const build=()=>{let html='';const root:any={get innerHTML(){return html},set innerHTML(value){html=value},querySelector(){return null},querySelectorAll(){return []}};const context=vm.createContext({applyQueueAvailability(){},document:{querySelector:()=>root},CSS:{escape:String},escapeHtml:String,relative:()=> '1m ago',roleName:String,statusName:String,stateClass:()=>'',actionLabel:{},brandIcon:()=>'',brandTitle:{},threadDrafts:new Map(),expandedThreadTurns:new Set(),collapsedThreadTurns:new Set(),latestThreadTurns:new Map(),threadResultViews:new Map(),threadResultContent:new Map()});vm.runInContext(source.split('\n').find(line=>line.startsWith('function promptReadableHtml('))!,context);const start=source.indexOf('function renderWorkflowThread('),end=source.indexOf('\nasync function loadWorkflowThread',start);vm.runInContext(source.slice(start,end),context);context.data={operator:{approver:true},actions:[],publication:null,turns:[{id:1,kind:'event',stage:'DESIGN',status:'QUEUED',reason:'Issue accepted',milestone:false},{id:2,kind:'execution',role:'product-architect',outcome:'spec',status:'succeeded',markdown:'# Spec',result:{outcome:'spec'},publication:{status:'published',url:'https://github.com/o/r/issues/1#issuecomment-5'},milestone:true},{id:3,kind:'human',login:'owner',command:'approve',source:'dashboard',text:'/factory approve v1',milestone:true},{id:4,kind:'execution',role:'developer',outcome:'pass',status:'succeeded',markdown:'# Build',result:{outcome:'pass'},milestone:false},{id:5,kind:'event',stage:'TEST',status:'QUEUED',reason:'Builder passed',milestone:false}]};return{context,read:()=>html}};
 const off=build();vm.runInContext("renderWorkflowThread('w',data)",off.context);const all=off.read();
 for(const key of ['w:1','w:2','w:3','w:4','w:5'])assert.match(all,new RegExp(`data-thread-turn="${key}"`));assert.match(all,/data-thread-filter\s+onchange/);assert.doesNotMatch(all,/data-thread-filter checked/);assert.match(all,/5 turns/);assert.doesNotMatch(all,/data-thread-turn="w:5"[^>]* open/,'a transition without a body stays closed');assert.match(all,/data-thread-turn="w:4"[^>]* open/);
 const on=build();on.context.threadMilestonesOnly=true;vm.runInContext("renderWorkflowThread('w',data)",on.context);const filtered=on.read();
 assert.match(filtered,/data-thread-filter checked/);assert.match(filtered,/2 of 5 turns/);for(const key of ['w:1','w:4','w:5'])assert.doesNotMatch(filtered,new RegExp(`data-thread-turn="${key}"`));assert.match(filtered,/data-thread-turn="w:3" open/);assert.match(filtered,/data-thread-turn="w:2"[^>]*>/);
 on.context.data.turns.push({id:6,kind:'execution',role:'product-architect',status:'running',startedAt:new Date().toISOString(),progress:{events:2,lastProgressAt:new Date().toISOString(),tool:'Bash',warning:'repeated-action'},milestone:false});vm.runInContext("renderWorkflowThread('w',data)",on.context);assert.match(on.read(),/3 of 6 turns/);assert.match(on.read(),/data-thread-turn="w:6"[^>]* open/);assert.match(on.read(),/Last observable activity 1m ago/);assert.match(on.read(),/Bash active/);assert.match(on.read(),/may need attention/);
 assert.match(source,/window\.toggleThreadFilter=toggleThreadFilter/);assert.match(source,/localStorage\.getItem\(threadFilterKey\)/);
});
test('a rejected execution and its automatic retry stay visible among key updates',()=>{
 let html='';const root:any={set innerHTML(value:string){html=value},querySelector(){return null},querySelectorAll(){return []}};const context=vm.createContext({applyQueueAvailability(){},document:{querySelector:()=>root},CSS:{escape:String},escapeHtml:String,relative:()=> '1m ago',roleName:()=> 'Architect',statusName:String,stateClass:()=>'',actionLabel:{},brandIcon:()=>'',brandTitle:{},threadDrafts:new Map(),expandedThreadTurns:new Set(),collapsedThreadTurns:new Set(),latestThreadTurns:new Map(),threadResultViews:new Map(),threadResultContent:new Map(),threadMilestonesOnly:true});vm.runInContext(source.split('\n').find(line=>line.startsWith('function promptReadableHtml('))!,context);const start=source.indexOf('function renderWorkflowThread('),end=source.indexOf('\nasync function loadWorkflowThread',start);vm.runInContext(source.slice(start,end),context);
 context.data={operator:{approver:true},actions:['retry'],turns:[{id:1,kind:'execution',role:'product-architect',status:'rejected',reason:'Result rejected: questions must be []',milestone:true},{id:2,kind:'event',stage:'DESIGN',status:'QUEUED',reason:'Result rejected; retrying once',milestone:true},{id:3,kind:'event',stage:'DESIGN',status:'RUNNING',reason:'Architect execution started',milestone:false}]};vm.runInContext("renderWorkflowThread('w',data)",context);assert.match(html,/2 of 3 turns/);assert.match(html,/Architect · rejected/);assert.match(html,/Result rejected: questions must be \[\]/);assert.match(html,/Result rejected; retrying once/);assert.doesNotMatch(html,/Architect execution started/);
});

test('the issue card answers in the dashboard and shows activity only when it adds information',()=>{
 const context=vm.createContext({escapeHtml:String,relative:()=>"3m ago",collapsedWorkDetails:new Set()});vm.runInContext(source.split('\n').find(line=>line.startsWith('function promptReadableHtml('))!,context);vm.runInContext(source.split('\n').find(line=>line.startsWith('function workDetails('))!,context);
 const render=(item:any)=>vm.runInContext("workDetails(item,new Set())",Object.assign(context,{item})) as string;
 assert.equal(render({id:'w',status:'WAITING',activity:{label:'Waiting for you',detail:'Branch published and pull request ready',blockers:[]}}),'','waiting repeats the conversation and the next step');
 assert.equal(render({id:'w',status:'QUEUED',activity:{label:'Queued',detail:'Waiting for the local scheduler and active repository control.'}}),'');
 assert.match(render({id:'w',status:'QUEUED',activity:{label:'Waiting for capacity',detail:'Another task is using the execution slot.'}}),/work-activity-line ">Another task is using the execution slot\.</);
 assert.match(render({id:'w',status:'RUNNING',activity:{label:'Agent running',detail:'Read is running',since:'t'}}),/>Read is running · started 3m ago/);
 assert.match(render({id:'w',status:'RUNNING',activity:{label:'Check agent progress',detail:'No observable progress for 5 minutes',since:'t',warning:true}}),/Interrupt or guide agent/);
 assert.match(render({id:'w',status:'RUNNING',activity:{label:'Needs recovery',detail:'The agent has finished, but the workflow has not advanced.',since:'t',stalled:true}}),/work-activity-line is-stalled">The agent has finished, but the workflow has not advanced\. · 3m ago</);
 const paused=render({id:'w',status:'PAUSED',activity:{label:'Paused',detail:'Human interrupted the active attempt',blockers:['Missing test for AC-2']}});
 assert.match(paused,/>Human interrupted the active attempt</);assert.match(paused,/<summary>Open findings \(1\)<\/summary>/);assert.doesNotMatch(render({id:'w',status:'WAITING',activity:{label:'Waiting for you',detail:'x'}}),/Activity details/);
 assert.doesNotMatch(source,/How to request changes|How to respond|Activity details/);
 assert.match(source,/class="next-step-respond" onclick="respondInDashboard\(/);assert.match(source,/Or post <code>/);assert.match(source,/window\.respondInDashboard=respondInDashboard/);
});

test('the conversation header explains a continuation and whether earlier turns live elsewhere',()=>{
 let html='';const root:any={get innerHTML(){return html},set innerHTML(value){html=value},querySelector(){return null},querySelectorAll(){return []}};
 const context=vm.createContext({applyQueueAvailability(){},document:{querySelector:()=>root},CSS:{escape:String},escapeHtml:String,relative:()=> '2h ago',roleName:String,statusName:String,stateClass:()=>'',actionLabel:{},brandIcon:()=>'',brandTitle:{},threadDrafts:new Map(),expandedThreadTurns:new Set(),collapsedThreadTurns:new Set(),latestThreadTurns:new Map(),threadResultViews:new Map(),threadResultContent:new Map()});vm.runInContext(source.split('\n').find(line=>line.startsWith('function promptReadableHtml('))!,context);const start=source.indexOf('function renderWorkflowThread('),end=source.indexOf('\nasync function loadWorkflowThread',start);vm.runInContext(source.slice(start,end),context);
 context.data={operator:{approver:true},actions:[],publication:null,continuations:[{at:'t',instance:'macbook-pro-7-local',revision:10,earlierTurns:false}],turns:[]};vm.runInContext("renderWorkflowThread('w',data)",context);
 assert.match(html,/<strong>Continued here<\/strong><span>From macbook-pro-7-local at revision 10 · 2h ago\. Earlier turns were recorded on macbook-pro-7-local; this installation started from the state published on the issue\.<\/span>/);
 assert.ok(html.indexOf('Continued here')<html.indexOf('workflow-thread"'),'the note sits above the turns');assert.match(html,/No turns on this installation yet\./);assert.match(html,/>0 turns</);context.data={...context.data,turns:[{id:7,kind:'human',login:'owner',command:'note',source:'dashboard',text:'Keep going',milestone:true}]};vm.runInContext("renderWorkflowThread('w',data)",context);assert.match(html,/>1 turn</);assert.doesNotMatch(html,/No workflow turns yet/);
 context.data={...context.data,continuations:[{at:'t',instance:'laptop',revision:3,earlierTurns:true},{at:'t',instance:'desktop',revision:null,earlierTurns:true}]};vm.runInContext("renderWorkflowThread('w',data)",context);
 assert.match(html,/From desktop · 2h ago\. It has moved between installations 2 times\./);assert.doesNotMatch(html,/Earlier turns were recorded/);
 context.data={...context.data,continuations:[]};vm.runInContext("renderWorkflowThread('w',data)",context);assert.doesNotMatch(html,/Continued here/);
});

test('the status comment note says when the next attempt happens, or that the daemon is stopped',()=>{
 let html='';const root:any={get innerHTML(){return html},set innerHTML(value){html=value},querySelector(){return null},querySelectorAll(){return []}};
 const context=vm.createContext({applyQueueAvailability(){},document:{querySelector:()=>root},CSS:{escape:String},escapeHtml:String,relative:()=> 'now',roleName:String,statusName:String,stateClass:()=>'',actionLabel:{},brandIcon:()=>'',brandTitle:{},threadDrafts:new Map(),expandedThreadTurns:new Set(),collapsedThreadTurns:new Set(),latestThreadTurns:new Map(),threadResultViews:new Map(),threadResultContent:new Map()});
 vm.runInContext(source.split('\n').find(line=>line.startsWith('function promptReadableHtml('))!,context);vm.runInContext(source.split('\n').find(line=>line.startsWith('function nextAttemptText('))!,context);const start=source.indexOf('function renderWorkflowThread('),end=source.indexOf('\nasync function loadWorkflowThread',start);vm.runInContext(source.slice(start,end),context);
 const failed={revision:3,publishedRevision:2,behind:true,url:null,error:'gh: HTTP 502: Bad Gateway (https://api.github.com/x)',attempts:3,needsAttention:true};
 const show=(sync:any)=>{context.data={operator:{approver:true},actions:[],publication:failed,sync,turns:[]};vm.runInContext("renderWorkflowThread('w',data)",context);return html;};
 const soon=new Date(Date.now()+12_400).toISOString();
 assert.match(show({state:'failed',nextAt:soon,daemonRunning:true}),new RegExp(`data-next-attempt="${soon}">Next attempt in 13 s\\.<`));
 assert.match(show({state:'failed',nextAt:new Date(Date.now()-1000).toISOString(),daemonRunning:true}),/>Next attempt starting\.</);
 assert.match(show({state:'syncing',nextAt:soon,daemonRunning:true}),/Retrying now\./);
 const stopped=show({state:'failed',nextAt:soon,daemonRunning:false});assert.match(stopped,/The daemon is stopped; publication resumes when it starts\./);assert.doesNotMatch(stopped,/Next attempt/);
 assert.match(show(undefined),/Retries on the next daemon cycle\./);
 context.data={operator:{approver:true},actions:[],publication:{...failed,error:null,attempts:0,needsAttention:false},sync:{state:'idle',nextAt:soon,daemonRunning:true},turns:[]};vm.runInContext("renderWorkflowThread('w',data)",context);assert.match(html,/Pending publication of the latest change\.<\/span>/);assert.doesNotMatch(html,/Next attempt/);
 assert.match(source,/setInterval\(\(\)=>\{for\(const node of document\.querySelectorAll\('\[data-next-attempt\]'\)\)/);
});

test('turns open only when they have a body and show the clock time once they are older than an hour',()=>{
 let html='';const root:any={get innerHTML(){return html},set innerHTML(value){html=value},querySelector(){return null},querySelectorAll(){return []}};
 const context=vm.createContext({applyQueueAvailability(){},document:{querySelector:()=>root},CSS:{escape:String},escapeHtml:String,relative:()=> '5m ago',roleName:String,statusName:String,stateClass:()=>'',actionLabel:{},brandIcon:()=>'',brandTitle:{},threadDrafts:new Map(),expandedThreadTurns:new Set(),collapsedThreadTurns:new Set(),latestThreadTurns:new Map(),threadResultViews:new Map(),threadResultContent:new Map()});vm.runInContext(source.split('\n').find(line=>line.startsWith('function promptReadableHtml('))!,context);const start=source.indexOf('function renderWorkflowThread('),end=source.indexOf('\nasync function loadWorkflowThread',start);vm.runInContext(source.slice(start,end),context);
 const now=Date.now(),recent=new Date(now-5*60000).toISOString(),earlier=new Date(now-2*3600000).toISOString(),lastWeek=new Date(now-8*86400000).toISOString();
 context.data={operator:{approver:true},actions:[],publication:null,turns:[{id:1,at:lastWeek,kind:'event',stage:'DESIGN',status:'QUEUED',reason:'Issue accepted'},{id:2,at:earlier,kind:'execution',role:'reviewer',outcome:'pass',status:'succeeded',markdown:'# Report',result:{outcome:'pass'}},{id:3,at:recent,kind:'event',stage:'DELIVERY',status:'WAITING',reason:'Pull request ready'}]};
 vm.runInContext("renderWorkflowThread('w',data)",context);
 assert.doesNotMatch(html,/data-thread-turn="w:3"[^>]* open/,'the newest turn has no body');assert.match(html,/data-thread-turn="w:2"[^>]* open/,'the newest turn with a body opens instead');
 assert.match(html,/Workflow · 5m ago/);assert.doesNotMatch(html,/Agent execution · 5m ago/);assert.match(html,/Agent execution · \d{2}:\d{2}:\d{2}</);assert.match(html,/Workflow · [A-Z][a-z]{2} \d{1,2} \d{2}:\d{2}:\d{2}</);
 assert.doesNotMatch(fs.readFileSync(new URL('../dashboard/styles.css',import.meta.url),'utf8'),/\.workflow-thread\{[^}]*max-height/,'the conversation does not scroll inside the page');assert.doesNotMatch(source,/threadScroll/);
});
