import {resultMarkdown} from "../src/workflow-github.js";
import test from 'node:test';import assert from 'node:assert/strict';
import {Store} from '../src/storage.js';import {WorkflowProjections} from '../src/workflow-projection.js';import {recoverLegacyResultPauses} from '../src/legacy-result-pauses.js';import {parseResult} from '../src/results.js';import {result} from './fixtures.js';
test('environment finding is accepted for decision but rejected as pass',()=>{const findings=[{classification:'environment-blocked' as const,evidence:'Browser launch failed'}];assert.equal(parseResult(result('decision',{findings}),'developer').findings[0].classification,'environment-blocked');assert.throws(()=>parseResult(result('pass',{findings}),'developer'),/Environment blockers/);});
test('legacy automatic result pauses become Failed once; intentional pauses remain paused',()=>{const store=new Store(':memory:');try{
 const projections=new WorkflowProjections(store);for(const id of ['legacy','human','maintenance']){store.db.prepare("INSERT INTO work_items(id,issue_number,repo,created_at,updated_at) VALUES(?,?,'owner/demo','now','now')").run(id,['legacy','human','maintenance'].indexOf(id)+1);projections.initialize(id,'BUILD','QUEUED');projections.transition({workItemId:id,expectedRevision:0,stage:'BUILD',status:'PAUSED',actor:{type:id==='human'?'human':'agent',id:id==='legacy'?'product-architect':id},source:{},reason:id==='legacy'?{code:'tactical-resolved',summary:'Architect reported unresolved prerequisites; work paused for review'}:{code:'pause',summary:'Intentional pause'}});}
 recoverLegacyResultPauses(store);recoverLegacyResultPauses(store);assert.equal(projections.get('legacy').status,'FAILED');assert.equal(projections.get('human').status,'PAUSED');assert.equal(projections.get('maintenance').status,'PAUSED');assert.equal((store.db.prepare('SELECT COUNT(*) n FROM failures').get() as any).n,1);
 }finally{store.db.close();}});

test('environment failure report tells the user to fix the cause and retry, without promising continuation',()=>{const markdown=resultMarkdown('developer',result('decision',{findings:[{classification:'environment-blocked',evidence:'Chrome cannot launch'}]}),1);assert.match(markdown,/Fix the reported environment issue, then Retry/);assert.doesNotMatch(markdown,/queued automatically|Builder continues/);});
