import test from "node:test";
import assert from "node:assert/strict";
import {Store} from "../src/storage.js";
import {WorkflowIntake,WorkflowInbox} from "../src/workflow-inbox.js";
import {WorkflowRecords} from "../src/workflow-records.js";
import {WorkflowFailures} from "../src/workflow-failures.js";
import {adoptIssueState,issueStateIndex,type SpecificationFact} from "../src/workflow-state.js";
import {WorkflowGitHubPublisher,payloadOf,readIssueState,withPayload} from "../src/workflow-github.js";

const issue={id:41,nodeId:"I_41",number:4,title:"Portable workflow",body:"Body stays on GitHub",url:"https://github.com/owner/demo/issues/4",state:"OPEN" as const,labels:[],assignees:["factory"],createdAt:"now",updatedAt:"now",author:{login:"owner",type:"User"}};
const identity={id:7,nodeId:"R_7",fullName:"owner/demo"};
function stateSource(){const store=new Store(":memory:");store.setMetadata("repository_identity",identity);const item=new WorkflowIntake(store).start(issue,{actor:"factory",source:"assignment",initialCursor:77});const fact:SpecificationFact={kind:"spec",version:1,body:"SPEC",stories:[],criteria:[{id:"AC1",description:"Works"}],assessment:{risk:"low"}};store.db.prepare("INSERT INTO specs(work_item_id,version,body,criteria,assessment,approved_by,approval_comment_id,approved_at) VALUES(?,?,?,?,?,?,?,?)").run(item.id,1,fact.body,JSON.stringify(fact.criteria),JSON.stringify(fact.assessment),"owner",50,"now");store.event("agent.result",{role:"product-architect",result:{outcome:"spec"},specVersion:1},item.id,"run-spec");return{store,item,fact};}

test("continuation keeps specifications, approvals, active records, failure and safe context",()=>{
 const source=stateSource(),target=new Store(":memory:");try{target.setMetadata("repository_identity",identity);const records=new WorkflowRecords(source.store),instruction=records.create({workItemId:source.item.id,specVersion:1,scope:"issue",payload:{kind:"instruction",text:"Preserve behavior"},sourceType:"github-comment",sourceId:"60",actor:"owner"}),request=records.create({workItemId:source.item.id,specVersion:1,scope:"spec",payload:{kind:"request",type:"clarification",owner:"human",originatingStage:"BUILD",allowedReturnStages:["BUILD"],openedAfterCommentId:70},sourceType:"agent-result",sourceId:"run",actor:"developer"}),failure=new WorkflowFailures(source.store).open({workItemId:source.item.id,class:"integration",message:"Resolve conflict",stage:"BUILD",attempt:2});source.store.db.prepare("UPDATE work_items SET stage='BUILD',status='PAUSED',attempt=2,revision=9,correction_cycles=1,active_request_id=?,active_failure_id=?,context=json_set(context,'$.verifiedHeads.TEST','abc','$.pr','https://github.com/owner/demo/pull/1','$.cwd','/private/worktree') WHERE id=?").run(request.id,failure.id,source.item.id);const projection=adoptIssueState(target,{index:issueStateIndex(source.store,source.item.id),specs:[source.fact]},{issue});assert.equal(projection.status,"PAUSED");assert.equal(projection.activeRequestId,request.id);assert.equal(projection.activeFailureId,failure.id);assert.equal((target.db.prepare("SELECT COUNT(*) n FROM executions").get() as any).n,0);assert.equal((target.db.prepare("SELECT COUNT(*) n FROM notifications").get() as any).n,0);assert.equal((target.db.prepare("SELECT approved_by FROM specs WHERE work_item_id=?").get(source.item.id) as any).approved_by,"owner");assert.equal(new WorkflowRecords(target).get(instruction.id)?.status,"active");const context=JSON.parse((target.db.prepare("SELECT context FROM work_items WHERE id=?").get(source.item.id) as any).context);assert.equal(context.cursor,77);assert.equal(context.verifiedHeads.TEST,"abc");assert.equal(context.cwd,undefined);assert.deepEqual(context.continuedFrom,{instance:issueStateIndex(source.store,source.item.id).instance,revision:9,publishedAt:context.continuedFrom.publishedAt});const event=JSON.parse((target.db.prepare("SELECT payload FROM events WHERE type='workflow.transition'").get() as any).payload);assert.equal(event.reason.code,"continued");assert.equal(event.actor.id,"continuation");}finally{source.store.db.close();target.db.close();}
});

test("continuation validates identity, preserves waiting freshness and pauses unfinished remote work",()=>{
 const source=stateSource(),target=new Store(":memory:");try{target.setMetadata("repository_identity",identity);const request=new WorkflowRecords(source.store).create({workItemId:source.item.id,specVersion:1,scope:"spec",payload:{kind:"request",type:"spec-approval",owner:"human",originatingStage:"DESIGN",allowedReturnStages:["BUILD"],openedAfterCommentId:100},sourceType:"agent-result",sourceId:"run",actor:"product-architect"});source.store.db.prepare("UPDATE work_items SET stage='DESIGN',status='WAITING',revision=4,active_request_id=? WHERE id=?").run(request.id,source.item.id);const state={index:issueStateIndex(source.store,source.item.id),specs:[source.fact]};assert.equal(adoptIssueState(target,state,{issue}).status,"WAITING");new WorkflowInbox(target,{comments:()=>[]},["owner"]).poll(source.item.id,[{id:99,body:"/factory approve v1",user:{login:"owner",type:"User"},updatedAt:"now"}]);assert.match(JSON.parse((target.db.prepare("SELECT payload FROM events WHERE type='command.stale'").get() as any).payload).error,/opened after comment 100/);const foreign=new Store(":memory:");foreign.setMetadata("repository_identity",{id:8,nodeId:"R_8",fullName:"other/demo"});assert.throws(()=>adoptIssueState(foreign,state,{issue}),/another repository/);assert.throws(()=>adoptIssueState(target,state,{issue:{...issue,id:999,nodeId:"I_999"}}),/another issue/);foreign.db.close();const active=structuredClone(state);active.index.projection.status="RUNNING";const activeTarget=new Store(":memory:");activeTarget.setMetadata("repository_identity",identity);assert.equal(adoptIssueState(activeTarget,active,{issue}).status,"PAUSED");activeTarget.db.close();}finally{source.store.db.close();target.db.close();}
});

test("reading issue state refuses a missing referenced specification comment",async()=>{
 const source=stateSource();try{const index=issueStateIndex(source.store,source.item.id),status=withPayload("status",index)+"\n<!-- ai-factory:workflow-status:owner/demo:4 -->",github={comments:async()=>[{id:1,body:status,user:{login:"factory",type:"User"},updatedAt:"now"}]};await assert.rejects(()=>readIssueState(github,4),/specification v1 is missing/);const spec=withPayload("spec",source.fact)+"\n<!-- ai-factory:workflow-comment:owner/demo:4:result-run-spec -->";github.comments=async()=>[{id:1,body:status,user:{login:"factory",type:"User"},updatedAt:"now"},{id:2,body:spec,user:{login:"factory",type:"User"},updatedAt:"now"}];assert.deepEqual(await readIssueState(github,4),{index,specs:[source.fact]});}finally{source.store.db.close();}
});

test("published specification markers survive two continuation hops and a return to the first installation",async()=>{
 const a=stateSource(),b=new Store(":memory:"),c=new Store(":memory:");try{for(const store of [b,c])store.setMetadata("repository_identity",identity);const specComment=withPayload("spec",a.fact)+"\n<!-- ai-factory:workflow-comment:owner/demo:4:result-run-spec -->",aIndex=issueStateIndex(a.store,a.item.id);adoptIssueState(b,{index:aIndex,specs:[a.fact]},{issue});let bStatus="";await new WorkflowGitHubPublisher(b,{syncWorkflow(_issue,_labels,body){bStatus=body;},publishWorkflowComment(){return 2;}}).publish(a.item.id);const bIndex=payloadOf(bStatus) as typeof aIndex;assert.equal(bIndex.specs[0].marker,"result-run-spec");const bComments={comments:async()=>[{id:1,body:bStatus+"\n<!-- ai-factory:workflow-status:owner/demo:4 -->",user:{login:"factory",type:"User"},updatedAt:"now"},{id:2,body:specComment,user:{login:"factory",type:"User"},updatedAt:"now"}]};const readByC=await readIssueState(bComments,4);assert.ok(readByC);adoptIssueState(c,readByC,{issue});assert.equal(issueStateIndex(c,a.item.id).specs[0].marker,"result-run-spec");b.db.prepare("UPDATE work_items SET revision=revision+2,presentation_revision=presentation_revision+2,published_presentation_revision=NULL WHERE id=?").run(a.item.id);await new WorkflowGitHubPublisher(b,{syncWorkflow(_issue,_labels,body){bStatus=body;},publishWorkflowComment(){return 2;}}).publish(a.item.id);const readBack=await readIssueState(bComments,4);assert.ok(readBack);adoptIssueState(a.store,readBack,{issue});assert.equal(issueStateIndex(a.store,a.item.id).specs[0].marker,"result-run-spec");}finally{a.store.db.close();b.db.close();c.db.close();}
});
