import test from "node:test";
import assert from "node:assert/strict";
import { Store } from "../src/storage.js";
import { WorkflowProjections } from "../src/workflow-projection.js";
import { WorkflowScheduler } from "../src/workflow-scheduler.js";
import { WorkflowFailures } from "../src/workflow-failures.js";

function setup(stage:"DESIGN"|"BUILD"="DESIGN",approved=false){const store=new Store(":memory:");store.db.prepare("INSERT INTO work_items(id,issue_number,repo,created_at,updated_at,context) VALUES('work-1',1,'owner/demo','now','now','{}')").run();if(approved)store.db.prepare("INSERT INTO specs(work_item_id,version,body,approved_by) VALUES('work-1',1,'SPEC','owner')").run();const projections=new WorkflowProjections(store);projections.initialize("work-1",stage,"QUEUED");return {store,projections,scheduler:new WorkflowScheduler(store)};}

test("scheduler atomically creates one execution and marks it active",()=>{const s=setup();try{const started=s.scheduler.begin("work-1");assert.equal(started.role,"product-architect");assert.deepEqual({status:started.projection.status,active:started.projection.activeRunId},{status:"RUNNING",active:started.executionId});assert.deepEqual(s.store.db.prepare("SELECT work_item_id,role,stage,status FROM executions WHERE id=?").get(started.executionId),{work_item_id:"work-1",role:"product-architect",stage:"DESIGN",status:"running"});assert.throws(()=>s.scheduler.begin("work-1"),/RUNNING/);}finally{s.store.db.close();}});

test("scheduler enforces approval and confirmed maintenance barrier",()=>{const unapproved=setup("BUILD");try{assert.throws(()=>unapproved.scheduler.begin("work-1"),/approved/);}finally{unapproved.store.db.close();}const blocked=setup("BUILD",true);try{blocked.store.db.prepare("INSERT INTO maintenance_operations(id,operation,actor,status,requested_at,confirmed_at) VALUES('m','update','owner','confirmed','now','now')").run();blocked.store.db.prepare("INSERT INTO maintenance_items(maintenance_id,work_item_id,confirmed_revision) VALUES('m','work-1',0)").run();assert.throws(()=>blocked.scheduler.begin("work-1"),/maintenance/);assert.equal(blocked.projections.get("work-1").status,"QUEUED");assert.equal((blocked.store.db.prepare("SELECT COUNT(*) count FROM executions").get() as {count:number}).count,0);}finally{blocked.store.db.close();}});

test("execution failure preserves stage and opens the selected failure atomically",()=>{const s=setup();try{const started=s.scheduler.begin("work-1"),failed=s.scheduler.fail("work-1",started.executionId,new Error("provider exited"));assert.equal(failed.discarded,false);assert.deepEqual({stage:failed.projection.stage,status:failed.projection.status,activeRun:failed.projection.activeRunId},{stage:"DESIGN",status:"FAILED",activeRun:undefined});assert.equal(new WorkflowFailures(s.store).active("work-1")?.id,failed.failureId);}finally{s.store.db.close();}});
