const $=selector=>document.querySelector(selector);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const relative=value=>{const seconds=Math.round((Date.now()-new Date(value).getTime())/1000);if(seconds<60)return `${seconds}s ago`;if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`};
const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};
async function control(kind,target=''){const response=await fetch('/api/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,target})});const result=await response.json();if(!response.ok)throw new Error(result.error);toast(result.message);await refresh()}
window.factoryControl=(kind,target)=>control(kind,target).catch(error=>toast(error.message));
function metric(items,states){return items.filter(item=>states.includes(item.state)).length}
function render(data){
  $('#repository').textContent=`${data.repository||'No repository configured'} · ${data.branch}`;
  $('#daemon-state').textContent=data.daemon.running?'Daemon running':'Daemon stopped';$('#daemon-pid').textContent=data.daemon.pid?`PID ${data.daemon.pid}`:'';$('#daemon-dot').classList.toggle('on',data.daemon.running);$('#stop').disabled=!data.daemon.running;
  $('#active-count').textContent=metric(data.items,['SPEC','DEVELOPMENT','QA','REVIEW']);$('#waiting-count').textContent=metric(data.items,['WAITING_HUMAN','PAUSED']);$('#ready-count').textContent=metric(data.items,['READY_TO_MERGE','MERGED']);$('#failed-count').textContent=metric(data.items,['FAILED','PR_CLOSED']);$('#updated').textContent=`Updated ${relative(data.generatedAt)}`;
  $('#items').innerHTML=data.items.length?data.items.map(item=>{const retry=['FAILED','CANCELLED','PAUSED'].includes(item.state)?`<button onclick="factoryControl('retry','${escapeHtml(item.id)}')">Retry</button>`:'';const cancel=['SPEC','WAITING_HUMAN','DEVELOPMENT','QA','REVIEW'].includes(item.state)?`<button class="danger" onclick="factoryControl('cancel','${escapeHtml(item.id)}')">Cancel</button>`:'';return `<article class="item"><div><a href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer">#${item.issue} ${escapeHtml(item.title||item.id)}</a><p>${escapeHtml(item.id)} · ${relative(item.updatedAt)}</p></div><span class="state">${escapeHtml(item.state)}</span><div class="actions">${retry}${cancel}</div></article>`}).join(''):'<p class="empty">No issues have entered the factory yet.</p>';
  $('#executions').innerHTML=data.executions.length?data.executions.map(run=>`<article class="entry"><div class="entry-head"><strong>${escapeHtml(run.role)}</strong><span class="state">${escapeHtml(run.status)}</span></div><p>${escapeHtml(run.work_item_id)} · ${relative(run.started_at)}${run.exit_code===null?'':` · exit ${run.exit_code}`}</p></article>`).join(''):'<p class="empty">No agent executions yet.</p>';
  $('#events').innerHTML=data.events.length?data.events.map(event=>`<article class="entry"><div class="entry-head"><strong>${escapeHtml(event.type)}</strong><span>${relative(event.ts)}</span></div><p>${escapeHtml(event.workItemId||'system')}${event.details?` · ${escapeHtml(event.details)}`:''}</p></article>`).join(''):'<p class="empty">No audit events yet.</p>';
}
async function refresh(){try{const response=await fetch('/api/snapshot');if(!response.ok)throw new Error('Dashboard API unavailable');render(await response.json())}catch(error){toast(error.message)}}
$('#stop').addEventListener('click',()=>control('stop').catch(error=>toast(error.message)));refresh();setInterval(refresh,5000);
