const $=selector=>document.querySelector(selector);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const relative=value=>{const seconds=Math.round((Date.now()-new Date(value).getTime())/1000);if(seconds<60)return `${seconds}s ago`;if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`};
const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};
const setupMode=new URLSearchParams(location.search).get('setup')==='1';
let settingsLoaded=false,activeSettingsGroup=setupMode?'credentials':null,credentialsData={credentials:[]},credentialBusy=false,slackData={configured:false,pending:0,failed:0,sent:0,lastError:null},slackBusy=false,settingsBusy=false,daemonRunning=false,pendingDashboardUrl=null;
const selectedTheme=()=>document.documentElement.dataset.theme||'dark';
function renderTheme(){const light=selectedTheme()==='light';$('#theme-toggle').textContent=light?'Dark mode':'Light mode';$('#theme-toggle').setAttribute('aria-pressed',String(light))}
$('#theme-toggle').addEventListener('click',()=>{const next=selectedTheme()==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem('factory-theme',next);renderTheme()});renderTheme();
async function control(kind,target=''){const response=await fetch('/api/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,target})});const result=await response.json();if(!response.ok)throw new Error(result.error);toast(result.message);await refresh()}
window.factoryControl=(kind,target)=>control(kind,target).catch(error=>toast(error.message));
window.refreshIssue=target=>{if(!confirm('Reload this issue from GitHub and evaluate only its latest comment? Previous comments and completed agent stages will not be replayed.'))return;control('refresh',target).catch(error=>toast(error.message))};
let serviceBusy=false;
let factoryUpdating=false,lastServices=null,loadedRevision=null,updateCheck=null,updateChecking=false;
async function serviceAction(service,action){if(serviceBusy||factoryUpdating)return;serviceBusy=true;try{if(lastServices)renderServices(lastServices);const response=await fetch('/api/services',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({service,action})});const data=await response.json();if(!response.ok)throw new Error(data.error);toast(data.message);if(service==='dashboard'&&action==='restart'&&pendingDashboardUrl)return setTimeout(()=>location.assign(pendingDashboardUrl),1800);setTimeout(loadServices,1200)}catch(error){toast(error.message)}finally{serviceBusy=false}}
window.serviceAction=serviceAction;
async function checkForUpdates(){if(factoryUpdating||updateChecking)return;updateChecking=true;if(lastServices)renderServices(lastServices);try{const response=await fetch('/api/update/check',{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.error);updateCheck=data}catch(error){updateCheck={error:error.message}}finally{updateChecking=false;if(lastServices)renderServices(lastServices)}}
async function updateFactory(){if(factoryUpdating)return;if(!updateCheck?.available)return checkForUpdates();factoryUpdating=true;if(lastServices)renderServices({...lastServices,update:{status:'updating',phase:'Preparing update…'}});let response;try{response=await fetch('/api/update',{method:'POST'})}catch{toast('Update connection interrupted; waiting for the dashboard to return.');return}try{const data=await response.json();if(!response.ok)throw new Error(data.error);if(lastServices)renderServices({...lastServices,update:data.update});toast(data.message)}catch(error){factoryUpdating=false;updateCheck=null;if(lastServices)renderServices(lastServices);toast(error.message)}}
function metric(items,states){return items.filter(item=>states.includes(item.state)).length}
const stateClass=value=>`state-${String(value).toLowerCase().replaceAll('_','-')}`;
function render(data){
  $('#repository').textContent=`${data.repository||'No repository configured'} · ${data.branch}`;
  $('#active-count').textContent=metric(data.items,['SPEC','DEVELOPMENT','QA','REVIEW']);$('#waiting-count').textContent=metric(data.items,['WAITING_HUMAN','PAUSED']);$('#ready-count').textContent=metric(data.items,['READY_TO_MERGE','MERGED']);$('#failed-count').textContent=metric(data.items,['FAILED','PR_CLOSED']);$('#updated').textContent=`Updated ${relative(data.generatedAt)}`;
  $('#items').innerHTML=data.items.length?data.items.map(item=>{const retry=['FAILED','CANCELLED','PAUSED'].includes(item.state)?`<button onclick="factoryControl('retry','${escapeHtml(item.id)}')">Retry</button>`:'';const cancel=['SPEC','WAITING_HUMAN','DEVELOPMENT','QA','REVIEW'].includes(item.state)?`<button class="danger" onclick="factoryControl('cancel','${escapeHtml(item.id)}')">Cancel</button>`:'';const refresh=`<button title="Reload issue data and evaluate only the latest GitHub comment" onclick="refreshIssue('${escapeHtml(item.id)}')">Refresh from GitHub</button>`;return `<article class="item"><div><a href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer">#${item.issue} ${escapeHtml(item.title||item.id)}</a><p>${escapeHtml(item.id)} · ${relative(item.updatedAt)}</p></div><span class="state ${stateClass(item.state)}"><i></i>${escapeHtml(item.state)}</span><div class="actions">${refresh}${retry}${cancel}</div></article>`}).join(''):'<p class="empty">No issues found. The factory reads open issues carrying the <code>factory:queued</code> label.</p>';
  const issueRefresh=data.issueRefresh,status=$('#issue-refresh-status'),refreshButton=$('#refresh-issue-list');status.textContent=issueRefresh?.message||'';status.className=issueRefresh?.status==='failed'?'refresh-result failed':'muted';refreshButton.disabled=issueRefresh?.status==='queued';
  $('#executions').innerHTML=data.executions.length?data.executions.map(run=>`<article class="entry"><div class="entry-head"><strong>${escapeHtml(run.role)}</strong><span class="state">${escapeHtml(run.status)}</span></div><p>${escapeHtml(run.work_item_id)} · ${relative(run.started_at)}${run.exit_code===null?'':` · exit ${run.exit_code}`}</p></article>`).join(''):'<p class="empty">No agent executions yet.</p>';
  $('#events').innerHTML=data.events.length?data.events.map(event=>`<article class="entry"><div class="entry-head"><strong>${escapeHtml(event.type)}</strong><span>${relative(event.ts)}</span></div><p>${escapeHtml(event.workItemId||'system')}${event.details?` · ${escapeHtml(event.details)}`:''}</p></article>`).join(''):'<p class="empty">No audit events yet.</p>';
  daemonRunning=data.daemon.running;applySettingsLock();
  if(!settingsBusy)$('#settings-status').textContent=data.daemon.running?'The daemon is running. Saving will validate the full configuration, restart it, and preserve its running state.':'Configuration is editable. Saving validates first; stopped services remain stopped.';
}
async function refresh(){try{const response=await fetch('/api/snapshot');if(!response.ok)throw new Error('Dashboard API unavailable');render(await response.json())}catch(error){toast(error.message)}}
function applySettingsLock(){document.querySelectorAll('[data-setting],[data-clear-secret],#settings-actions button[type="submit"]').forEach(control=>control.disabled=settingsBusy);document.querySelectorAll('[data-slack-edit]').forEach(control=>control.disabled=slackBusy)}
function credentialCards(data){return data.credentials.map(item=>{const connected=item.status==='connected',connecting=item.status==='connecting',failed=item.status==='failed';const state=connected?'Connected':connecting?'Connecting…':failed?'Login failed':'Not connected';const stateClassName=connected?'state-merged':connecting?'state-paused':failed?'state-failed':'state-cancelled';const action=connected?'Reconnect':'Connect';return `<article class="credential-card"><div class="credential-copy"><div><h4>${escapeHtml(item.label)}</h4><span class="state ${stateClassName}"><i></i>${state}</span></div><p>${escapeHtml(item.description)}</p>${item.account?`<strong class="credential-account">${escapeHtml(item.account)}</strong>`:''}${failed?`<small>Open the credential log for details, then retry.</small>`:''}</div><button type="button" onclick="connectCredential('${escapeHtml(item.id)}')" ${credentialBusy||connecting||!item.installed?'disabled':''}>${!item.installed?'CLI unavailable':connecting?'Waiting for browser…':action}</button></article>`}).join('')}
function slackCredentialCard(){const state=slackData.configured?'Connected':'Not connected',stateClassName=slackData.configured?'state-merged':'state-cancelled';return `<article class="credential-card"><div class="credential-copy"><div><h4>Slack</h4><span class="state ${stateClassName}"><i></i>${state}</span></div><p>Incoming webhook for state changes, failures and queued workflow notifications.</p>${slackData.configured?`<strong class="credential-account">${slackData.pending} pending · ${slackData.failed} failed · ${slackData.sent} sent</strong>`:''}</div><button type="button" onclick="openSlackSettings()">${slackData.configured?'Manage':'Configure'}</button></article>`}
function renderCredentials(data){credentialsData=data;const list=$('#credentials-list');if(list)list.innerHTML=credentialCards(data)+slackCredentialCard();const log=$('#credentials-log');if(log)log.textContent=data.log||'.factory/service-logs/credentials.log'}
async function loadCredentials(){try{const wasConnected=credentialsData.credentials.find(item=>item.id==='github')?.status==='connected';const response=await fetch('/api/credentials');const data=await response.json();if(!response.ok)throw new Error(data.error);renderCredentials(data);if(settingsLoaded&&!wasConnected&&data.credentials.find(item=>item.id==='github')?.status==='connected')await loadSettings()}catch(error){if($('#credentials-list'))$('#credentials-list').innerHTML=`<p class="empty">${escapeHtml(error.message)}</p>`}}
async function connectCredential(provider){if(credentialBusy)return;credentialBusy=true;renderCredentials(credentialsData);try{const response=await fetch('/api/credentials/connect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({provider})});const data=await response.json();if(!response.ok)throw new Error(data.error);toast(data.message);await loadCredentials()}catch(error){toast(error.message)}finally{credentialBusy=false;await loadCredentials()}}
window.connectCredential=connectCredential;
function renderSlack(data){slackData=data;const root=$('#slack-connection');if(!root)return;const state=data.configured?'Connected':'Not connected',stateClassName=data.configured?'state-merged':'state-cancelled';root.innerHTML=`<div class="slack-status"><div><span class="state ${stateClassName}"><i></i>${state}</span><h4>Slack delivery</h4><p>The webhook stays in <code>.env</code> and is never sent back to this page. Configure it above, then use the global Save and apply action.</p></div><dl><div><dt>Pending</dt><dd>${data.pending}</dd></div><div><dt>Failed</dt><dd>${data.failed}</dd></div><div><dt>Sent</dt><dd>${data.sent}</dd></div></dl></div>${data.lastError?`<div class="slack-error"><strong>Last delivery error</strong><p>${escapeHtml(data.lastError)}</p></div>`:''}<div class="slack-actions"><button type="button" onclick="testSlack()" ${!data.configured||slackBusy?'disabled':''}>${slackBusy?'Sending…':'Send test notification'}</button></div><p class="muted">To disconnect Slack, select “Clear configured secret” above and use Save and apply.</p>`;applySettingsLock();renderCredentials(credentialsData)}
async function loadSlack(){try{const response=await fetch('/api/slack');const data=await response.json();if(!response.ok)throw new Error(data.error);renderSlack(data)}catch(error){if($('#slack-connection'))$('#slack-connection').innerHTML=`<p class="empty">${escapeHtml(error.message)}</p>`}}
async function testSlack(){if(slackBusy)return;slackBusy=true;renderSlack(slackData);try{const response=await fetch('/api/slack/test',{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.error);renderSlack(data);toast(data.message)}catch(error){toast(error.message)}finally{slackBusy=false;await loadSlack()}}
function openSlackSettings(){activeSettingsGroup='notifications';document.querySelector('[data-settings-tab="notifications"]')?.click()}
window.testSlack=testSlack;window.openSlackSettings=openSlackSettings;
function renderSetupGuide(readiness){const guide=$('#setup-guide'),list=$('#setup-requirements');if(!guide||!list)return;const missing=readiness?.missing||[];guide.hidden=Boolean(readiness?.ready||!missing.length);list.innerHTML=missing.map(item=>`<li>${escapeHtml(item.label)}</li>`).join('')}
function renderSettings(data){
  const grouped=new Map(data.groups.map(group=>[group.id,[]]));for(const field of data.fields){if(!grouped.has(field.group))grouped.set(field.group,[]);grouped.get(field.group).push(field)}
  const available=data.groups.filter(group=>['credentials','notifications'].includes(group.id)||grouped.get(group.id)?.length);if(!available.some(group=>group.id===activeSettingsGroup))activeSettingsGroup=data.readiness?.missing?.[0]?.group||available[0]?.id;
  const restartLabel=value=>value==='all'?'Restart both services':value==='dashboard'?'Restart dashboard':'Restart daemon';
  const control=field=>{if(field.type==='select'){const roleAttrs=field.kind==='provider'?` data-role-provider="${escapeHtml(field.role)}"`:field.kind==='role-model'?` data-role-model="${escapeHtml(field.role)}"`:'';return `<select data-setting="${escapeHtml(field.key)}"${roleAttrs} ${field.required?'required':''}>${field.options.map(option=>`<option value="${escapeHtml(option.value)}" ${option.value===field.value?'selected':''}>${escapeHtml(option.label)}</option>`).join('')}</select>`}return `<div class="input-wrap"><input data-setting="${escapeHtml(field.key)}" type="${field.secret?'password':field.type==='number'?'number':'text'}" value="${escapeHtml(field.value)}" ${field.required?'required':''} autocomplete="off" placeholder="${field.secret&&field.configured?'Configured — blank keeps current value':''}">${field.unit?`<span>${escapeHtml(field.unit)}</span>`:''}</div>`};
  const fieldCard=field=>`<label class="setting-card ${['provider','role-model'].includes(field.kind)?'provider-setting':''}"><span class="setting-label"><strong>${escapeHtml(field.label)}</strong><span>${field.required?'<b>Required</b>':''}${field.suggested?'<i>Suggested default</i>':''}${field.restart?`<i>${restartLabel(field.restart)}</i>`:''}</span></span><small>${escapeHtml(field.description)}</small>${control(field)}<code>${escapeHtml(field.key)}</code>${field.secret&&field.configured?`<em><input data-clear-secret="${escapeHtml(field.key)}" type="checkbox"> Clear configured secret</em>`:''}</label>`;
  $('#settings-navigation').innerHTML=available.map(group=>{const count=group.id==='credentials'?credentialsData.credentials.length+1:group.id==='notifications'?1:grouped.get(group.id).length;const noun=group.id==='credentials'?'connections':group.id==='notifications'?'integration':count===1?'setting':'settings';return `<button type="button" role="tab" aria-selected="${group.id===activeSettingsGroup}" data-settings-tab="${escapeHtml(group.id)}"><strong>${escapeHtml(group.label)}</strong><small>${count} ${noun}</small></button>`}).join('');
  $('#settings-groups').innerHTML=available.map(group=>{let content;if(group.id==='credentials')content=`<div class="credentials-intro"><p>Authenticate this Mac through each provider's official CLI. Credentials remain in the provider's local secure store and are never displayed by the factory.</p><button type="button" onclick="loadSettings()">Refresh status</button></div><div id="credentials-list" class="credentials-grid">${credentialCards(credentialsData)+slackCredentialCard()}</div><p class="credential-log muted">Login output: <code id="credentials-log">${escapeHtml(credentialsData.log||'.factory/service-logs/credentials.log')}</code></p>`;else if(group.id==='notifications')content=`<div class="settings-grid">${grouped.get(group.id).map(fieldCard).join('')}</div><div id="slack-connection"></div>`;else if(group.id==='models'){const sections=[...new Set(grouped.get(group.id).map(field=>field.section))];content=`<div class="role-routing-grid">${sections.map(section=>`<section class="role-routing-card"><div class="role-routing-title"><p class="eyebrow">AGENT ROLE</p><h4>${escapeHtml(section)}</h4></div><div class="role-settings-grid">${grouped.get(group.id).filter(field=>field.section===section).map(fieldCard).join('')}</div></section>`).join('')}</div>`}else content=`<div class="settings-grid">${grouped.get(group.id).map(fieldCard).join('')}</div>`;return `<section class="settings-group" data-settings-panel="${escapeHtml(group.id)}" ${group.id===activeSettingsGroup?'':'hidden'}><div class="settings-group-title"><h3>${escapeHtml(group.label)}</h3><p>${escapeHtml(group.description)}</p></div>${content}</section>`}).join('');
  document.querySelectorAll('[data-role-provider]').forEach(select=>select.addEventListener('change',()=>{const catalog=data.modelCatalog[select.value];document.querySelectorAll(`[data-role-model="${select.dataset.roleProvider}"]`).forEach(model=>{model.innerHTML=catalog.options.map(option=>`<option value="${escapeHtml(option.value)}" ${option.value===catalog.default?'selected':''}>${escapeHtml(option.label)}</option>`).join('')})}));
  const selectGroup=id=>{activeSettingsGroup=id;document.querySelectorAll('[data-settings-tab]').forEach(tab=>tab.setAttribute('aria-selected',String(tab.dataset.settingsTab===id)));document.querySelectorAll('[data-settings-panel]').forEach(panel=>panel.hidden=panel.dataset.settingsPanel!==id);$('#settings-actions').hidden=id==='credentials';if(id==='notifications')loadSlack()};
  document.querySelectorAll('[data-settings-tab]').forEach(button=>button.addEventListener('click',()=>selectGroup(button.dataset.settingsTab)));selectGroup(activeSettingsGroup);
  $('#settings-summary').textContent=`${available.length} categories · ${data.fields.length} variables`;daemonRunning=data.daemonRunning;renderSetupGuide(data.readiness);applySettingsLock();$('#settings-change-status').textContent='Values are validated before affected running services restart automatically.';settingsLoaded=true;
}
async function loadSettings(){try{const [settingsResponse,credentialsResponse,slackResponse]=await Promise.all([fetch('/api/settings'),fetch('/api/credentials'),fetch('/api/slack')]);const data=await settingsResponse.json(),credentials=await credentialsResponse.json(),slack=await slackResponse.json();if(!settingsResponse.ok)throw new Error(data.error);if(!credentialsResponse.ok)throw new Error(credentials.error);if(!slackResponse.ok)throw new Error(slack.error);credentialsData=credentials;slackData=slack;renderSettings(data)}catch(error){toast(error.message)}}
if(setupMode){const panel=document.querySelector('.settings-panel');panel.open=true;setTimeout(()=>panel.scrollIntoView({behavior:'smooth',block:'start'}),100)}
function renderServices(data){if(loadedRevision&&data.version?.revision&&loadedRevision!==data.version.revision)return location.reload();if(!loadedRevision&&data.version?.revision)loadedRevision=data.version.revision;lastServices=data;factoryUpdating=data.update?.status==='updating';const locked=serviceBusy||factoryUpdating;const update=$('#update-status'),button=$('#factory-update');$('#factory-version').textContent=data.version?.display||'Version unavailable';const phaseAge=factoryUpdating&&data.update.startedAt?` · started ${relative(data.update.startedAt)}`:'';update.textContent=factoryUpdating?`${data.update.phase||'Updating…'}${phaseAge}`:data.update?.status==='failed'?data.update.phase||'Update failed':updateChecking?'Checking origin…':updateCheck?.error?'Update check failed':updateCheck?.available?`New version ${updateCheck.latest} available`:updateCheck?'Up to date':'Not checked';update.title=factoryUpdating?'The current phase and elapsed time update automatically. See .factory/service-logs/update.log for live command output.':data.update?.status==='failed'?'See .factory/service-logs/update.log for full details.':'';update.className=factoryUpdating?'state state-paused':data.update?.status==='failed'||updateCheck?.error?'state state-failed':updateCheck?.available?'state state-paused':'muted';button.textContent=factoryUpdating?'Updating…':updateChecking?'Checking…':updateCheck?.available?'Update Factory':updateCheck?'Check again':'Check for updates';button.disabled=locked||updateChecking;$('#services').innerHTML=data.services.map(service=>{const status=factoryUpdating?'Updating…':service.running?'Running':service.loaded?'Loaded':'Stopped';const color=factoryUpdating?'state-paused':service.running?'state-merged':service.loaded?'state-paused':'state-cancelled';return `<article class="service-card"><div><span class="state ${color}"><i></i>${status}</span><h3>${escapeHtml(service.service)}</h3></div><div class="service-actions"><button onclick="serviceAction('${escapeHtml(service.service)}','start')" ${service.running||locked?'disabled':''}>Start</button><button onclick="serviceAction('${escapeHtml(service.service)}','restart')" ${locked?'disabled':''}>Restart</button><button class="danger" onclick="serviceAction('${escapeHtml(service.service)}','stop')" ${service.loaded&&!locked?'':'disabled'}>Stop</button></div></article>`}).join('')}
async function loadServices(){try{const response=await fetch('/api/services');const data=await response.json();if(!response.ok)throw new Error(data.error);renderServices(data)}catch(error){if(factoryUpdating){$('#update-status').textContent='Updating… waiting for dashboard';$('#live-status').textContent='Reconnecting';$('#live-status').classList.remove('connected')}else if(!lastServices){$('#services').innerHTML=`<p class="empty">${escapeHtml(error.message)}</p>`}}}
$('#settings-form').addEventListener('change',()=>{$('#settings-change-status').textContent='Unsaved changes';$('#settings-change-status').classList.add('changed')});
$('#settings-form').addEventListener('submit',async event=>{event.preventDefault();if(settingsBusy)return;settingsBusy=true;applySettingsLock();$('#settings-status').textContent='Validating configuration before saving…';try{const values=Object.fromEntries([...document.querySelectorAll('[data-setting]')].map(input=>[input.dataset.setting,input.value]));const clearSecrets=[...document.querySelectorAll('[data-clear-secret]:checked')].map(input=>input.dataset.clearSecret);const response=await fetch('/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({values,clearSecrets})});const data=await response.json();if(!response.ok)throw new Error(data.error);const host=values.FACTORY_DASHBOARD_HOST,port=values.FACTORY_DASHBOARD_PORT,displayHost=host==='::1'?'[::1]':host;pendingDashboardUrl=`http://${displayHost}:${port}/`;renderSettings(data);$('#settings-change-status').classList.remove('changed');$('#settings-status').textContent=data.message;if(data.dashboardRestarting){$('#settings-change-status').innerHTML=`Dashboard is restarting. If this page does not reconnect, <a href="${escapeHtml(pendingDashboardUrl)}">open ${escapeHtml(pendingDashboardUrl)}</a>.`;setTimeout(()=>location.assign(pendingDashboardUrl),1800)}else pendingDashboardUrl=null;toast(data.message)}catch(error){$('#settings-status').textContent=`Configuration was not saved: ${error.message}`;toast(error.message)}finally{settingsBusy=false;applySettingsLock()}});
function live(){const stream=new EventSource('/api/stream');stream.onopen=()=>{$('#live-status').textContent='Live';$('#live-status').classList.add('connected')};stream.onmessage=event=>{try{render(JSON.parse(event.data))}catch{}};stream.onerror=()=>{$('#live-status').textContent='Reconnecting';$('#live-status').classList.remove('connected')}}
window.loadCredentials=loadCredentials;window.loadSlack=loadSlack;window.loadSettings=loadSettings;$('#factory-update').addEventListener('click',updateFactory);refresh();live();loadServices().then(checkForUpdates);if(!settingsLoaded)loadSettings();setInterval(refresh,15000);setInterval(loadServices,2000);setInterval(loadCredentials,10000);setInterval(loadSlack,10000);setInterval(checkForUpdates,300000);
