const $=selector=>document.querySelector(selector);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const relative=value=>{const seconds=Math.round((Date.now()-new Date(value).getTime())/1000);if(seconds<60)return `${seconds}s ago`;if(seconds<3600)return `${Math.floor(seconds/60)}m ago`;if(seconds<86400)return `${Math.floor(seconds/3600)}h ago`;return `${Math.floor(seconds/86400)}d ago`};
const toast=message=>{const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)};
let settingsLoaded=false;
const selectedTheme=()=>document.documentElement.dataset.theme||'dark';
function renderTheme(){const light=selectedTheme()==='light';$('#theme-toggle').textContent=light?'Dark mode':'Light mode';$('#theme-toggle').setAttribute('aria-pressed',String(light))}
$('#theme-toggle').addEventListener('click',()=>{const next=selectedTheme()==='light'?'dark':'light';document.documentElement.dataset.theme=next;localStorage.setItem('factory-theme',next);renderTheme()});renderTheme();
async function control(kind,target=''){const response=await fetch('/api/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,target})});const result=await response.json();if(!response.ok)throw new Error(result.error);toast(result.message);await refresh()}
window.factoryControl=(kind,target)=>control(kind,target).catch(error=>toast(error.message));
let serviceBusy=false;
async function serviceAction(service,action){if(serviceBusy)return;serviceBusy=true;try{await loadServices();const response=await fetch('/api/services',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({service,action})});const data=await response.json();if(!response.ok)throw new Error(data.error);toast(data.message);setTimeout(loadServices,1200)}catch(error){toast(error.message)}finally{serviceBusy=false}}
window.serviceAction=serviceAction;
function metric(items,states){return items.filter(item=>states.includes(item.state)).length}
const stateClass=value=>`state-${String(value).toLowerCase().replaceAll('_','-')}`;
function render(data){
  $('#repository').textContent=`${data.repository||'No repository configured'} · ${data.branch}`;
  $('#active-count').textContent=metric(data.items,['SPEC','DEVELOPMENT','QA','REVIEW']);$('#waiting-count').textContent=metric(data.items,['WAITING_HUMAN','PAUSED']);$('#ready-count').textContent=metric(data.items,['READY_TO_MERGE','MERGED']);$('#failed-count').textContent=metric(data.items,['FAILED','PR_CLOSED']);$('#updated').textContent=`Updated ${relative(data.generatedAt)}`;
  $('#items').innerHTML=data.items.length?data.items.map(item=>{const retry=['FAILED','CANCELLED','PAUSED'].includes(item.state)?`<button onclick="factoryControl('retry','${escapeHtml(item.id)}')">Retry</button>`:'';const cancel=['SPEC','WAITING_HUMAN','DEVELOPMENT','QA','REVIEW'].includes(item.state)?`<button class="danger" onclick="factoryControl('cancel','${escapeHtml(item.id)}')">Cancel</button>`:'';return `<article class="item"><div><a href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer">#${item.issue} ${escapeHtml(item.title||item.id)}</a><p>${escapeHtml(item.id)} · ${relative(item.updatedAt)}</p></div><span class="state ${stateClass(item.state)}"><i></i>${escapeHtml(item.state)}</span><div class="actions">${retry}${cancel}</div></article>`}).join(''):'<p class="empty">No issues have entered the factory yet.</p>';
  $('#executions').innerHTML=data.executions.length?data.executions.map(run=>`<article class="entry"><div class="entry-head"><strong>${escapeHtml(run.role)}</strong><span class="state">${escapeHtml(run.status)}</span></div><p>${escapeHtml(run.work_item_id)} · ${relative(run.started_at)}${run.exit_code===null?'':` · exit ${run.exit_code}`}</p></article>`).join(''):'<p class="empty">No agent executions yet.</p>';
  $('#events').innerHTML=data.events.length?data.events.map(event=>`<article class="entry"><div class="entry-head"><strong>${escapeHtml(event.type)}</strong><span>${relative(event.ts)}</span></div><p>${escapeHtml(event.workItemId||'system')}${event.details?` · ${escapeHtml(event.details)}`:''}</p></article>`).join(''):'<p class="empty">No audit events yet.</p>';
  $('#settings-fieldset').disabled=data.daemon.running;
  $('#settings-status').textContent=data.daemon.running?'Stop the daemon to edit configuration. The dashboard can remain running.':'Configuration can be edited safely while the daemon is stopped.';
}
async function refresh(){try{const response=await fetch('/api/snapshot');if(!response.ok)throw new Error('Dashboard API unavailable');render(await response.json())}catch(error){toast(error.message)}}
function renderSettings(data){
  const groups=new Map();for(const field of data.fields){if(!groups.has(field.group))groups.set(field.group,[]);groups.get(field.group).push(field)}
  $('#settings-groups').innerHTML=[...groups].map(([name,fields])=>`<section class="settings-group"><h3>${escapeHtml(name)}</h3><div class="settings-grid">${fields.map(field=>`<label><span>${escapeHtml(field.label)}${field.required?' <b>required</b>':''}</span><small>${escapeHtml(field.description)}</small><input data-setting="${escapeHtml(field.key)}" type="${field.secret?'password':field.type==='number'?'number':'text'}" value="${escapeHtml(field.value)}" ${field.required?'required':''} autocomplete="off" placeholder="${field.secret&&field.configured?'Configured — blank keeps current value':''}">${field.secret&&field.configured?`<em><input data-clear-secret="${escapeHtml(field.key)}" type="checkbox"> Clear configured secret</em>`:''}</label>`).join('')}</div></section>`).join('');
  $('#settings-fieldset').disabled=data.daemonRunning;settingsLoaded=true;
}
async function loadSettings(){try{const response=await fetch('/api/settings');const data=await response.json();if(!response.ok)throw new Error(data.error);renderSettings(data)}catch(error){toast(error.message)}}
async function loadServices(){try{const response=await fetch('/api/services');const data=await response.json();if(!response.ok)throw new Error(data.error);$('#services').innerHTML=data.services.map(service=>{const status=service.running?'Running':service.loaded?'Loaded':'Stopped';return `<article class="service-card"><div><span class="state ${service.running?'state-merged':service.loaded?'state-paused':'state-cancelled'}"><i></i>${status}</span><h3>${escapeHtml(service.service)}</h3></div><div class="service-actions"><button onclick="serviceAction('${escapeHtml(service.service)}','start')" ${service.running||serviceBusy?'disabled':''}>Start</button><button title="Update the whole Factory and restore running services" onclick="serviceAction('${escapeHtml(service.service)}','update')" ${serviceBusy?'disabled':''}>Update</button><button onclick="serviceAction('${escapeHtml(service.service)}','restart')" ${serviceBusy?'disabled':''}>Restart</button><button class="danger" onclick="serviceAction('${escapeHtml(service.service)}','stop')" ${service.loaded&&!serviceBusy?'':'disabled'}>Stop</button></div></article>`}).join('')}catch(error){$('#services').innerHTML=`<p class="empty">${escapeHtml(error.message)}</p>`}}
$('#settings-form').addEventListener('submit',async event=>{event.preventDefault();try{const values=Object.fromEntries([...document.querySelectorAll('[data-setting]')].map(input=>[input.dataset.setting,input.value]));const clearSecrets=[...document.querySelectorAll('[data-clear-secret]:checked')].map(input=>input.dataset.clearSecret);const response=await fetch('/api/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({values,clearSecrets})});const data=await response.json();if(!response.ok)throw new Error(data.error);renderSettings(data);toast(data.message)}catch(error){toast(error.message)}});
function live(){const stream=new EventSource('/api/stream');stream.onopen=()=>{$('#live-status').textContent='Live';$('#live-status').classList.add('connected')};stream.onmessage=event=>{try{render(JSON.parse(event.data))}catch{}};stream.onerror=()=>{$('#live-status').textContent='Reconnecting';$('#live-status').classList.remove('connected')}}
refresh();live();loadServices();if(!settingsLoaded)loadSettings();setInterval(refresh,15000);setInterval(loadServices,5000);
