import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {config,requiredRepoDir} from "./config.js";
import type {Store} from "./storage.js";
import {WorkflowProjections} from "./workflow-projection.js";

type Result={status:number|null;stdout:string;stderr:string};
const redact=(value:string)=>value.replace(/(https?:\/\/)[^/@\s]+@/g,"$1***@");
function run(cwd:string,args:string[],allow=false):Result{const result=spawnSync(config.gitCommand,args,{cwd,encoding:"utf8",timeout:60_000,maxBuffer:10_000_000});const value={status:result.status,stdout:result.stdout??"",stderr:result.stderr??""};if(!allow&&result.status!==0)throw new Error(redact((value.stderr||value.stdout||`git ${args.join(" ")} failed`).trim()));return value;}
const normalized=(value:string)=>value.trim().replace(/^git@github\.com:/,"https://github.com/").replace(/\.git$/i,"").replace(/\/$/,"").toLowerCase();
const safeRelative=(parent:string,child:string)=>{const relative=path.relative(parent,child);return relative&&!relative.startsWith("..")&&!path.isAbsolute(relative);};

export interface RepositoryCheck {root:string;exists:boolean;empty:boolean;git:boolean;origin?:string;originMatches:boolean;branch?:string;defaultBranch:string;upstream?:string;head?:string;trackingHead?:string;remoteHead?:string;dirty:string[];untracked:string[];unpushed:number;behindTracking:number;worktrees:string[];inconsistencies:string[];recommendation:string;}

export class RepositoryMaintenance {
 constructor(private store:Store){}
 check():RepositoryCheck {
  const root=path.resolve(requiredRepoDir()),exists=fs.existsSync(root),empty=exists&&fs.statSync(root).isDirectory()&&fs.readdirSync(root).length===0,base:RepositoryCheck={root,exists,empty,git:false,originMatches:false,defaultBranch:config.defaultBranch,dirty:[],untracked:[],unpushed:0,behindTracking:0,worktrees:[],inconsistencies:[],recommendation:"Restore from remote"};
  if(!exists||empty)return base;if(!fs.statSync(root).isDirectory()){base.inconsistencies.push("Configured repository path is not a directory");base.recommendation="Fix the configured repository path";return base;}
  if(run(root,["rev-parse","--is-inside-work-tree"],true).stdout.trim()!=="true"){base.inconsistencies.push("Configured directory is not a Git repository");base.recommendation="Clear the local copy, then restore from remote";return base;}
  base.git=true;base.origin=run(root,["config","--get","remote.origin.url"],true).stdout.trim();base.originMatches=normalized(base.origin)===normalized(`https://github.com/${config.repo}`);base.branch=run(root,["branch","--show-current"],true).stdout.trim();base.upstream=run(root,["rev-parse","--abbrev-ref","--symbolic-full-name","@{upstream}"],true).stdout.trim()||undefined;base.head=run(root,["rev-parse","HEAD"]).stdout.trim();
  const status=run(root,["status","--porcelain=v1","-z"]).stdout.split("\0").filter(Boolean);base.dirty=status.filter(line=>!line.startsWith("?? "));base.untracked=status.filter(line=>line.startsWith("?? ")).map(line=>line.slice(3));
  const tracking=`origin/${config.defaultBranch}`,trackingResult=run(root,["rev-parse","--verify",tracking],true);if(trackingResult.status===0){base.trackingHead=trackingResult.stdout.trim();const counts=run(root,["rev-list","--left-right","--count",`${tracking}...HEAD`],true).stdout.trim().split(/\s+/).map(Number);base.behindTracking=counts[0]||0;base.unpushed=counts[1]||0;}
  const remote=run(root,["ls-remote","--heads","origin",`refs/heads/${config.defaultBranch}`],true);base.remoteHead=remote.stdout.trim().split(/\s+/)[0]||undefined;base.worktrees=run(root,["worktree","list","--porcelain"],true).stdout.split(/\r?\n/).filter(line=>line.startsWith("worktree ")).map(line=>line.slice(9));
  if(!base.originMatches)base.inconsistencies.push("Origin does not match the configured repository");if(base.branch!==config.defaultBranch)base.inconsistencies.push(`Configured checkout is on ${base.branch||"a detached HEAD"}, expected ${config.defaultBranch}`);if(!base.remoteHead)base.inconsistencies.push(`Remote base branch ${config.defaultBranch} does not exist`);if(base.remoteHead&&!base.trackingHead)base.inconsistencies.push("The remote default branch exists but has no local tracking ref");if(base.remoteHead&&base.trackingHead&&base.remoteHead!==base.trackingHead)base.inconsistencies.push("The local tracking ref is stale; Sync is required for an exact comparison");
  base.recommendation=!base.originMatches?"Fix origin before any mutation":!base.remoteHead?`Create and push the configured base branch ${config.defaultBranch} before starting the factory`:base.dirty.length||base.untracked.length?"Review or remove local changes before Sync":base.unpushed?"Publish or preserve unpushed commits before Sync":base.remoteHead!==base.head?"Sync from remote":"Repository is synchronized";return base;
 }
 sync(actor="cli") {const before=this.check();if(!before.git||!before.originMatches)throw new Error("Repository and origin must pass Check before Sync");if(before.branch!==config.defaultBranch)throw new Error(`Sync requires the ${config.defaultBranch} branch`);if(before.dirty.length||before.untracked.length)throw new Error("Sync refuses a dirty or untracked working tree");run(before.root,["fetch","--prune","origin"]);const remote=`origin/${config.defaultBranch}`,head=run(before.root,["rev-parse","HEAD"]).stdout.trim(),remoteHead=run(before.root,["rev-parse",remote]).stdout.trim();if(head!==remoteHead){if(run(before.root,["merge-base","--is-ancestor",head,remote],true).status!==0)throw new Error("Sync refuses local commits or divergent history");run(before.root,["merge","--ff-only",remote]);}const after=this.check();this.store.event("repository.operation.sync",{actor,before:this.summary(before),after:this.summary(after)});return after;}
 publish(workItemId:string,actor="cli") {const row=this.store.db.prepare("SELECT branch,context FROM work_items WHERE id=?").get(workItemId) as {branch:string|null;context:string}|undefined;if(!row)throw new Error("Unknown work item");if(this.store.db.prepare("SELECT 1 FROM executions WHERE work_item_id=? AND status='running'").get(workItemId))throw new Error("Publish refuses while the selected work item is running");if(!row.branch?.startsWith("factory/")||row.branch===config.defaultBranch)throw new Error("Publish accepts only the selected factory branch");const context=JSON.parse(row.context||"{}") as {cwd?:string};if(!context.cwd)throw new Error("Work item has no local worktree");const cwd=path.resolve(context.cwd);if(!safeRelative(path.resolve(config.dataDir,"worktrees"),cwd))throw new Error("Worktree is outside the factory-owned directory");if(run(cwd,["branch","--show-current"]).stdout.trim()!==row.branch)throw new Error("Worktree branch does not match the selected work item");const before={head:run(cwd,["rev-parse","HEAD"]).stdout.trim(),files:run(cwd,["status","--porcelain=v1"]).stdout.trim().split(/\r?\n/).filter(Boolean)};run(cwd,["add","--all"]);if(run(cwd,["diff","--cached","--quiet"],true).status!==0)run(cwd,["commit","-m",`factory: publish work item ${workItemId}`]);run(cwd,["push","--set-upstream","origin",`HEAD:refs/heads/${row.branch}`]);const after={head:run(cwd,["rev-parse","HEAD"]).stdout.trim()};this.store.event("repository.operation.publish",{actor,workItemId,branch:row.branch,before,after},workItemId);return{...after,branch:row.branch};}
 clear(confirmPath:string,repeatPath:string,actor="cli") {const root=this.safeRoot(confirmPath,repeatPath);const before=this.check();if(!before.git&&!before.exists)throw new Error("Configured repository directory does not exist");if(this.store.db.prepare("SELECT 1 FROM executions WHERE status='running'").get())throw new Error("Clear refuses while an execution is running; pause active tasks first");if(before.git){
   for(const directory of before.worktrees){
    if(!fs.existsSync(directory))continue;
    if(run(directory,["status","--porcelain=v1"]).stdout.trim())throw new Error("Clear blocked: local files have changes that are not committed. Commit and publish them, or save a copy before clearing.");
   }
   if(run(root,["rev-list","--branches","--not","--remotes"]).stdout.trim())throw new Error("Clear blocked: local branches contain unpublished commits. Publish or back them up before clearing.");
  }
  for(const worktree of before.worktrees)if(worktree!==root&&safeRelative(path.resolve(config.dataDir,"worktrees"),path.resolve(worktree)))fs.rmSync(worktree,{recursive:true,force:true});for(const entry of fs.readdirSync(root))fs.rmSync(path.join(root,entry),{recursive:true,force:true});const projections=new WorkflowProjections(this.store),affected:string[]=[];for(const row of this.store.db.prepare("SELECT id,status,context FROM work_items WHERE status NOT IN ('COMPLETED','CANCELLED')").all() as Array<{id:string;status:string;context:string}>){const current=projections.get(row.id);const mutate=()=>{const context=JSON.parse(row.context||"{}");delete context.cwd;this.store.db.prepare("UPDATE work_items SET context=? WHERE id=?").run(JSON.stringify(context),row.id);};if(current.status==="PAUSED")projections.present({workItemId:row.id,expectedRevision:current.revision,actor:{type:"human",id:actor},source:{},reason:{code:"repository-cleared",summary:"Local repository was cleared; restore and retry"}},mutate);else projections.transition({workItemId:row.id,expectedRevision:current.revision,stage:current.stage,status:"PAUSED",actor:{type:"human",id:actor},source:{},reason:{code:"repository-cleared",summary:"Local repository was cleared; restore and retry"}},mutate);affected.push(row.id);}this.store.event("repository.operation.clear",{actor,path:root,before:this.summary(before),after:{empty:true},affected});return{root,affected,empty:true};}
 restore(actor="cli") {const root=path.resolve(requiredRepoDir());if(fs.existsSync(root)&&fs.readdirSync(root).length)throw new Error("Restore requires an empty target directory");fs.mkdirSync(path.dirname(root),{recursive:true});if(fs.existsSync(root))fs.rmdirSync(root);run(path.dirname(root),["clone","--branch",config.defaultBranch,"--single-branch",`https://github.com/${config.repo}.git`,root]);const after=this.check();if(!after.originMatches||after.branch!==config.defaultBranch){fs.rmSync(root,{recursive:true,force:true});throw new Error("Restored checkout did not match the configured origin and default branch");}this.store.event("repository.operation.restore",{actor,path:root,after:this.summary(after)});return after;}
 private safeRoot(first:string,second:string){const root=path.resolve(requiredRepoDir()),home=path.resolve(os.homedir()),install=path.resolve(process.cwd()),data=path.resolve(config.dataDir);if(path.resolve(first)!==root||path.resolve(second)!==root)throw new Error(`Clear requires the exact configured path twice: ${root}`);if(root===path.parse(root).root||root===home||root===install||root===data||safeRelative(root,install)||safeRelative(root,data))throw new Error("Configured repository root overlaps a protected directory");if(fs.existsSync(root)&&fs.lstatSync(root).isSymbolicLink())throw new Error("Clear refuses a symlinked repository root");return root;}
 private summary(value:RepositoryCheck){return{root:value.root,head:value.head,remoteHead:value.remoteHead,branch:value.branch,dirty:value.dirty,untracked:value.untracked,unpushed:value.unpushed,behindTracking:value.behindTracking,originMatches:value.originMatches};}
}
