import {config} from "./config.js";
import type {Store} from "./storage.js";
import type {StoredRepositoryIdentity} from "./repository-identity.js";
import type {V3Stage} from "./workflow-records.js";
import type {V3Status} from "./workflow-projection.js";

export interface IssueStateIndex {
 kind:"state";schemaVersion:1;repository:{id:number;nodeId:string;fullName:string};issue:{id:number;nodeId:string;number:number};workflowId:string;instance:string;publishedAt:string;branch:string;
 projection:{stage:V3Stage;status:V3Status;attempt:number;revision:number;correctionCycles:number};
 context:{cursor?:number;observedComments?:unknown[];lastCommand?:unknown;verifiedHeads?:unknown;pr?:string;releasedAt?:string;title?:string;url?:string};
 specs:Array<{version:number;marker:string;approvedBy:string|null;approvalCommentId:number|null;approvedAt:string|null}>;
 records:Array<{id:string;work_item_id:string;sequence:number;kind:string;spec_version:number;scope:string;status:string;applies_to:unknown[];payload:Record<string,unknown>;source_type:string;source_id:string;actor:string;parent_id:string|null;superseded_by:string|null;resolved_by:null;created_at:string;updated_at:string}>;
 failure:{id:string;work_item_id:string;class:string;message:string;stage:string;attempt:number;created_at:string;resolved_at:string|null;resolved_by:string|null}|null;
}

const stages=new Set(["DESIGN","BUILD","TEST","REVIEW","DELIVERY"]),statuses=new Set(["QUEUED","RUNNING","WAITING","FAILED","PAUSED","CANCELLED","COMPLETED"]);
const object=(value:unknown,label:string):Record<string,unknown>=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`Invalid issue state ${label}`);return value as Record<string,unknown>;};
const exact=(value:Record<string,unknown>,allowed:string[],label:string)=>{for(const key of Object.keys(value))if(!allowed.includes(key))throw new Error(`Unknown issue state ${label} key: ${key}`);};
const text=(value:unknown,label:string)=>{if(typeof value!=="string")throw new Error(`Invalid issue state ${label}`);return value;};
const integer=(value:unknown,label:string)=>{if(!Number.isSafeInteger(value))throw new Error(`Invalid issue state ${label}`);return value as number;};
const nullableText=(value:unknown,label:string)=>value===null?null:text(value,label);

export function validateIssueState(value:unknown):IssueStateIndex {
 const root=object(value,"index");exact(root,["kind","schemaVersion","repository","issue","workflowId","instance","publishedAt","branch","projection","context","specs","records","failure"],"top-level");if(root.kind!=="state"||root.schemaVersion!==1)throw new Error("Unsupported issue state schema");
 const repository=object(root.repository,"repository");exact(repository,["id","nodeId","fullName"],"repository");integer(repository.id,"repository.id");text(repository.nodeId,"repository.nodeId");text(repository.fullName,"repository.fullName");const issue=object(root.issue,"issue");exact(issue,["id","nodeId","number"],"issue");integer(issue.id,"issue.id");text(issue.nodeId,"issue.nodeId");integer(issue.number,"issue.number");for(const key of ["workflowId","instance","publishedAt","branch"] as const)text(root[key],key);
 const projection=object(root.projection,"projection");exact(projection,["stage","status","attempt","revision","correctionCycles"],"projection");if(!stages.has(String(projection.stage))||!statuses.has(String(projection.status)))throw new Error("Invalid issue state projection");for(const key of ["attempt","revision","correctionCycles"] as const)integer(projection[key],`projection.${key}`);
 const context=object(root.context,"context");exact(context,["cursor","observedComments","lastCommand","verifiedHeads","pr","releasedAt","title","url"],"context");if(context.cursor!==undefined)integer(context.cursor,"context.cursor");if(context.observedComments!==undefined&&!Array.isArray(context.observedComments))throw new Error("Invalid issue state context.observedComments");for(const key of ["pr","releasedAt","title","url"] as const)if(context[key]!==undefined)text(context[key],`context.${key}`);
 if(!Array.isArray(root.specs)||!Array.isArray(root.records))throw new Error("Invalid issue state collections");for(const raw of root.specs){const spec=object(raw,"spec");exact(spec,["version","marker","approvedBy","approvalCommentId","approvedAt"],"spec");integer(spec.version,"spec.version");text(spec.marker,"spec.marker");nullableText(spec.approvedBy,"spec.approvedBy");if(spec.approvalCommentId!==null)integer(spec.approvalCommentId,"spec.approvalCommentId");nullableText(spec.approvedAt,"spec.approvedAt");}
 for(const raw of root.records){const record=object(raw,"record");exact(record,["id","work_item_id","sequence","kind","spec_version","scope","status","applies_to","payload","source_type","source_id","actor","parent_id","superseded_by","resolved_by","created_at","updated_at"],"record");for(const key of ["id","work_item_id","kind","scope","status","source_type","source_id","actor","created_at","updated_at"] as const)text(record[key],`record.${key}`);if(record.work_item_id!==root.workflowId)throw new Error("Issue state record belongs to another workflow");integer(record.sequence,"record.sequence");integer(record.spec_version,"record.spec_version");if(!Array.isArray(record.applies_to))throw new Error("Invalid issue state record.applies_to");object(record.payload,"record.payload");nullableText(record.parent_id,"record.parent_id");nullableText(record.superseded_by,"record.superseded_by");if(record.resolved_by!==null)throw new Error("Issue state records cannot reference local executions");}
 if(root.failure!==null){const failure=object(root.failure,"failure");exact(failure,["id","work_item_id","class","message","stage","attempt","created_at","resolved_at","resolved_by"],"failure");for(const key of ["id","work_item_id","class","message","stage","created_at"] as const)text(failure[key],`failure.${key}`);integer(failure.attempt,"failure.attempt");nullableText(failure.resolved_at,"failure.resolved_at");nullableText(failure.resolved_by,"failure.resolved_by");}
 return value as IssueStateIndex;
}

export function issueStateIndex(store:Store,workItemId:string):IssueStateIndex {
 const item=store.db.prepare("SELECT id,issue_number,issue_id,branch,context,stage,status,attempt,revision,correction_cycles FROM work_items WHERE id=?").get(workItemId) as any;if(!item)throw new Error("Unknown work item");const repository=store.metadata<StoredRepositoryIdentity>("repository_identity");if(!repository)throw new Error("Repository identity is not initialized");const source=JSON.parse(item.context||"{}") as Record<string,unknown>,context:Record<string,unknown>={};for(const key of ["cursor","observedComments","lastCommand","verifiedHeads","pr","releasedAt","title","url"])if(source[key]!==undefined)context[key]=source[key];const issueNodeId=text(source.issueNodeId,"issue.nodeId");
 const resultRows=store.db.prepare("SELECT run_id,payload FROM events WHERE work_item_id=? AND type='agent.result' ORDER BY id").all(workItemId) as Array<{run_id:string;payload:string}>,markers=new Map<number,string>();for(const row of resultRows)try{const payload=JSON.parse(row.payload) as {role?:string;result?:{outcome?:string};specVersion?:number};if(payload.role==="product-architect"&&payload.result?.outcome==="spec"&&payload.specVersion)markers.set(payload.specVersion,`result-${row.run_id}`);}catch{}
 const specs=(store.db.prepare("SELECT version,approved_by,approval_comment_id,approved_at FROM specs WHERE work_item_id=? ORDER BY version").all(workItemId) as any[]).map(spec=>({version:spec.version,marker:markers.get(spec.version)??`result-spec-v${spec.version}`,approvedBy:spec.approved_by,approvalCommentId:spec.approval_comment_id,approvedAt:spec.approved_at}));const records=(store.db.prepare("SELECT id,work_item_id,sequence,kind,spec_version,scope,status,applies_to,payload,source_type,source_id,actor,parent_id,superseded_by,created_at,updated_at FROM records WHERE work_item_id=? AND status IN ('active','open') ORDER BY sequence").all(workItemId) as any[]).map(record=>({...record,applies_to:JSON.parse(record.applies_to),payload:JSON.parse(record.payload),resolved_by:null}));const failure=store.db.prepare("SELECT id,work_item_id,class,message,stage,attempt,created_at,resolved_at,resolved_by FROM failures WHERE work_item_id=? AND resolved_at IS NULL").get(workItemId) as any??null;
 return validateIssueState({kind:"state",schemaVersion:1,repository,issue:{id:item.issue_id,nodeId:issueNodeId,number:item.issue_number},workflowId:item.id,instance:config.instanceName,publishedAt:new Date().toISOString(),branch:item.branch,projection:{stage:item.stage,status:item.status,attempt:item.attempt,revision:item.revision,correctionCycles:item.correction_cycles},context,specs,records,failure});
}
