import {config} from "./config.js";
import type {Store} from "./storage.js";
import type {StoredRepositoryIdentity} from "./repository-identity.js";
import type {V3Stage} from "./workflow-records.js";
import type {V3Status} from "./workflow-projection.js";
import {WorkflowProjections} from "./workflow-projection.js";
import type {Issue} from "./adapters/github.js";
import type {AgentResult,AgentRole} from "./types.js";
import {budgetLedger,validBudgetEntry,type BudgetEntry} from "./budget.js";

export interface PublishedLatestResult {role:AgentRole;executionId:string;outcome:AgentResult["outcome"];summary:string;coverage:AgentResult["coverage"];tests:AgentResult["tests"];changedFiles:string[];findings:AgentResult["findings"];decisions:AgentResult["decisions"]}

export interface IssueStateIndex {
 kind:"state";schemaVersion:1;repository:{id:number;nodeId:string;fullName:string};issue:{id:number;nodeId:string;number:number};workflowId:string;instance:string;publishedAt:string;branch:string;base:string;
 projection:{stage:V3Stage;status:V3Status;attempt:number;revision:number;correctionCycles:number};
 context:{cursor?:number;observedComments?:unknown[];lastCommand?:unknown;verifiedHeads?:unknown;pr?:string;releasedAt?:string;title?:string;url?:string;budgetUsage?:BudgetEntry[]};
 specs:Array<{version:number;marker:string;approvedBy:string|null;approvalCommentId:number|null;approvedAt:string|null}>;
 latestResults:PublishedLatestResult[];
 records:Array<{id:string;work_item_id:string;sequence:number;kind:string;spec_version:number;scope:string;status:string;applies_to:unknown[];payload:Record<string,unknown>;source_type:string;source_id:string;actor:string;parent_id:string|null;superseded_by:string|null;resolved_by:null;created_at:string;updated_at:string}>;
 failure:{id:string;work_item_id:string;class:string;message:string;stage:string;attempt:number;created_at:string;resolved_at:string|null;resolved_by:string|null}|null;
}
export interface SpecificationFact {kind:"spec";version:number;body:string;criteria:unknown[];assessment:unknown|null}
export interface ReadIssueState {index:IssueStateIndex;specs:SpecificationFact[]}
export class IncompleteIssueStateError extends Error {constructor(message:string){super(message);this.name="IncompleteIssueStateError";}}

const stages=new Set(["DESIGN","BUILD","TEST","REVIEW","DELIVERY"]),statuses=new Set(["QUEUED","RUNNING","WAITING","FAILED","PAUSED","CANCELLED","COMPLETED"]);
const object=(value:unknown,label:string):Record<string,unknown>=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error(`Invalid issue state ${label}`);return value as Record<string,unknown>;};
const exact=(value:Record<string,unknown>,allowed:string[],label:string)=>{for(const key of Object.keys(value))if(!allowed.includes(key))throw new Error(`Unknown issue state ${label} key: ${key}`);};
const text=(value:unknown,label:string)=>{if(typeof value!=="string")throw new Error(`Invalid issue state ${label}`);return value;};
const integer=(value:unknown,label:string)=>{if(!Number.isSafeInteger(value))throw new Error(`Invalid issue state ${label}`);return value as number;};
const nullableText=(value:unknown,label:string)=>value===null?null:text(value,label);

export function validateIssueState(value:unknown):IssueStateIndex {
 const root=object(value,"index");exact(root,["kind","schemaVersion","repository","issue","workflowId","instance","publishedAt","branch","base","projection","context","specs","latestResults","records","failure"],"top-level");if(root.kind!=="state"||root.schemaVersion!==1)throw new Error("Unsupported issue state schema");
 const repository=object(root.repository,"repository");exact(repository,["id","nodeId","fullName"],"repository");integer(repository.id,"repository.id");text(repository.nodeId,"repository.nodeId");text(repository.fullName,"repository.fullName");const issue=object(root.issue,"issue");exact(issue,["id","nodeId","number"],"issue");integer(issue.id,"issue.id");text(issue.nodeId,"issue.nodeId");integer(issue.number,"issue.number");for(const key of ["workflowId","instance","publishedAt","branch","base"] as const)text(root[key],key);
 const projection=object(root.projection,"projection");exact(projection,["stage","status","attempt","revision","correctionCycles"],"projection");if(!stages.has(String(projection.stage))||!statuses.has(String(projection.status)))throw new Error("Invalid issue state projection");for(const key of ["attempt","revision","correctionCycles"] as const)integer(projection[key],`projection.${key}`);
 const context=object(root.context,"context");exact(context,["cursor","observedComments","lastCommand","verifiedHeads","pr","releasedAt","title","url","budgetUsage"],"context");if(context.budgetUsage!==undefined&&(!Array.isArray(context.budgetUsage)||!context.budgetUsage.every(validBudgetEntry)))throw new Error("Invalid issue state context.budgetUsage");if(context.cursor!==undefined)integer(context.cursor,"context.cursor");if(context.observedComments!==undefined&&!Array.isArray(context.observedComments))throw new Error("Invalid issue state context.observedComments");for(const key of ["pr","releasedAt","title","url"] as const)if(context[key]!==undefined)text(context[key],`context.${key}`);
 if(!Array.isArray(root.specs)||!Array.isArray(root.latestResults)||!Array.isArray(root.records))throw new Error("Invalid issue state collections");for(const raw of root.specs){const spec=object(raw,"spec");exact(spec,["version","marker","approvedBy","approvalCommentId","approvedAt"],"spec");integer(spec.version,"spec.version");text(spec.marker,"spec.marker");nullableText(spec.approvedBy,"spec.approvedBy");if(spec.approvalCommentId!==null)integer(spec.approvalCommentId,"spec.approvalCommentId");nullableText(spec.approvedAt,"spec.approvedAt");}
 for(const raw of root.latestResults){const result=object(raw,"latest result");exact(result,["role","executionId","outcome","summary","coverage","tests","changedFiles","findings","decisions"],"latest result");if(!["product-architect","designer","developer","qa","reviewer"].includes(String(result.role)))throw new Error("Invalid issue state latest result role");if(!["spec","questions","resolved","pass","changes","decision"].includes(String(result.outcome)))throw new Error("Invalid issue state latest result outcome");text(result.executionId,"latest result executionId");text(result.summary,"latest result summary");for(const key of ["coverage","tests","changedFiles","findings","decisions"] as const)if(!Array.isArray(result[key]))throw new Error(`Invalid issue state latest result ${key}`);}
 for(const raw of root.records){const record=object(raw,"record");exact(record,["id","work_item_id","sequence","kind","spec_version","scope","status","applies_to","payload","source_type","source_id","actor","parent_id","superseded_by","resolved_by","created_at","updated_at"],"record");for(const key of ["id","work_item_id","kind","scope","status","source_type","source_id","actor","created_at","updated_at"] as const)text(record[key],`record.${key}`);if(record.work_item_id!==root.workflowId)throw new Error("Issue state record belongs to another workflow");integer(record.sequence,"record.sequence");integer(record.spec_version,"record.spec_version");if(!Array.isArray(record.applies_to))throw new Error("Invalid issue state record.applies_to");object(record.payload,"record.payload");nullableText(record.parent_id,"record.parent_id");nullableText(record.superseded_by,"record.superseded_by");if(record.resolved_by!==null)throw new Error("Issue state records cannot reference local executions");}
 if(root.failure!==null){const failure=object(root.failure,"failure");exact(failure,["id","work_item_id","class","message","stage","attempt","created_at","resolved_at","resolved_by"],"failure");for(const key of ["id","work_item_id","class","message","stage","created_at"] as const)text(failure[key],`failure.${key}`);integer(failure.attempt,"failure.attempt");nullableText(failure.resolved_at,"failure.resolved_at");nullableText(failure.resolved_by,"failure.resolved_by");}
 return value as IssueStateIndex;
}

// The index is what lets this issue be recovered from GitHub, and it only grows: agent summaries
// and finding evidence run to thousands of characters each. Dropping it whole once it crosses the
// body limit loses recovery for the rest of the issue's life, silently, because the issue body
// still looks complete. Narrative text is shed instead, because recovery reads identifiers,
// versions, statuses and markers, never prose.
const narrativeKeys=new Set(["summary","evidence","rationale","decision","text","message","command","questions","reason"]);
export const stateTextBudgets=[2000,500,120,0] as const;

function clip(value:unknown,budget:number,key?:string):unknown {
 if (typeof value==="string") return key && narrativeKeys.has(key) && value.length>budget ? (budget===0 ? "" : `${value.slice(0,budget)}…`) : value;
 // An array inherits its field name, so questions[] is clipped and changedFiles[] is not.
 if (Array.isArray(value)) return value.map(item=>clip(item,budget,key));
 if (value && typeof value==="object") return Object.fromEntries(Object.entries(value).map(([name,item])=>[name,clip(item,budget,name)]));
 return value;
}

export interface CompactedIssueState { index:IssueStateIndex; clippedTo:number|null }
export function compactIssueState(index:IssueStateIndex,fits:(candidate:IssueStateIndex)=>boolean):CompactedIssueState|null {
 if (fits(index)) return {index,clippedTo:null};
 for (const budget of stateTextBudgets) {
  const candidate=clip(index,budget) as IssueStateIndex;
  if (fits(candidate)) return {index:validateIssueState(candidate),clippedTo:budget};
 }
 return null;
}

export function issueStateIndex(store:Store,workItemId:string):IssueStateIndex {
 const item=store.db.prepare("SELECT id,issue_number,issue_id,branch,base_branch,context,stage,status,attempt,revision,correction_cycles FROM work_items WHERE id=?").get(workItemId) as any;if(!item)throw new Error("Unknown work item");const repository=store.metadata<StoredRepositoryIdentity>("repository_identity");if(!repository)throw new Error("Repository identity is not initialized");const source=JSON.parse(item.context||"{}") as Record<string,unknown>,context:Record<string,unknown>={};for(const key of ["cursor","observedComments","lastCommand","verifiedHeads","pr","releasedAt","title","url"])if(source[key]!==undefined)context[key]=source[key];const budgetUsage=budgetLedger(store,workItemId);if(budgetUsage.length)context.budgetUsage=budgetUsage;const issueNodeId=text(source.issueNodeId,"issue.nodeId");
 const resultRows=store.db.prepare("SELECT run_id,payload FROM events WHERE work_item_id=? AND type='agent.result' ORDER BY id").all(workItemId) as Array<{run_id:string;payload:string}>,storedMarkers=source.specMarkers&&typeof source.specMarkers==="object"&&!Array.isArray(source.specMarkers)?source.specMarkers as Record<string,unknown>:{},markers=new Map<number,string>(),latestByRole=new Map<AgentRole,PublishedLatestResult>();for(const value of Array.isArray(source.latestResults)?source.latestResults:[])try{const checked=validateLatestResult(value);latestByRole.set(checked.role,checked);}catch{}for(const [version,marker] of Object.entries(storedMarkers))if(/^\d+$/.test(version)&&typeof marker==="string")markers.set(Number(version),marker);for(const row of resultRows)try{const payload=JSON.parse(row.payload) as {role?:AgentRole;result?:AgentResult;specVersion?:number};if(payload.role==="product-architect"&&payload.result?.outcome==="spec"&&payload.specVersion&&!markers.has(payload.specVersion))markers.set(payload.specVersion,`result-${row.run_id}`);if(payload.role&&payload.result){const latest=publishedResult(payload.role,row.run_id,payload.result);validateLatestResult(latest);latestByRole.set(payload.role,latest);}}catch{}
 const specs=(store.db.prepare("SELECT version,approved_by,approval_comment_id,approved_at FROM specs WHERE work_item_id=? ORDER BY version").all(workItemId) as any[]).map(spec=>{const marker=markers.get(spec.version);if(!marker)throw new IncompleteIssueStateError(`Specification v${spec.version} has no published marker`);return{version:spec.version,marker,approvedBy:spec.approved_by,approvalCommentId:spec.approval_comment_id,approvedAt:spec.approved_at};});const records=(store.db.prepare("SELECT id,work_item_id,sequence,kind,spec_version,scope,status,applies_to,payload,source_type,source_id,actor,parent_id,superseded_by,created_at,updated_at FROM records WHERE work_item_id=? AND status IN ('active','open') ORDER BY sequence").all(workItemId) as any[]).map(record=>({...record,applies_to:JSON.parse(record.applies_to),payload:JSON.parse(record.payload),resolved_by:null}));const failure=store.db.prepare("SELECT id,work_item_id,class,message,stage,attempt,created_at,resolved_at,resolved_by FROM failures WHERE work_item_id=? AND resolved_at IS NULL").get(workItemId) as any??null;
 return validateIssueState({kind:"state",schemaVersion:1,repository,issue:{id:item.issue_id,nodeId:issueNodeId,number:item.issue_number},workflowId:item.id,instance:config.instanceName,publishedAt:new Date().toISOString(),branch:item.branch,base:item.base_branch,projection:{stage:item.stage,status:item.status,attempt:item.attempt,revision:item.revision,correctionCycles:item.correction_cycles},context,specs,latestResults:[...latestByRole.values()],records,failure});
}

function publishedResult(role:AgentRole,executionId:string,result:AgentResult):PublishedLatestResult{return{role,executionId,outcome:result.outcome,summary:result.summary,coverage:result.coverage,tests:result.tests,changedFiles:result.changedFiles,findings:result.findings,decisions:result.decisions};}
function validateLatestResult(value:unknown):PublishedLatestResult {const result=object(value,"latest result");exact(result,["role","executionId","outcome","summary","coverage","tests","changedFiles","findings","decisions"],"latest result");if(!["product-architect","designer","developer","qa","reviewer"].includes(String(result.role)))throw new Error("Invalid issue state latest result role");if(!["spec","questions","resolved","pass","changes","decision"].includes(String(result.outcome)))throw new Error("Invalid issue state latest result outcome");text(result.executionId,"latest result executionId");text(result.summary,"latest result summary");for(const key of ["coverage","tests","changedFiles","findings","decisions"] as const)if(!Array.isArray(result[key]))throw new Error(`Invalid issue state latest result ${key}`);return value as PublishedLatestResult;}

export function validateSpecificationFact(value:unknown):SpecificationFact {const spec=object(value,"specification payload");exact(spec,["kind","version","body","criteria","assessment"],"specification payload");if(spec.kind!=="spec")throw new Error("Invalid specification payload kind");integer(spec.version,"specification version");text(spec.body,"specification body");if(!Array.isArray(spec.criteria))throw new Error("Invalid specification criteria");return value as SpecificationFact;}

export function adoptIssueState(store:Store,state:ReadIssueState,options:{issue:Pick<Issue,"id"|"nodeId"|"number"|"title"|"url">}) {
 const index=validateIssueState(state.index),repository=store.metadata<StoredRepositoryIdentity>("repository_identity");if(!repository||repository.id!==index.repository.id)throw new Error("Published state belongs to another repository");if(options.issue.id!==index.issue.id||options.issue.nodeId!==index.issue.nodeId||options.issue.number!==index.issue.number)throw new Error("Published state belongs to another issue");const facts=state.specs.map(validateSpecificationFact),byVersion=new Map(facts.map(spec=>[spec.version,spec]));for(const spec of index.specs)if(!byVersion.has(spec.version))throw new Error(`Missing specification v${spec.version}`);
 return store.db.transaction(()=>{const existing=store.db.prepare("SELECT id FROM work_items WHERE id=?").get(index.workflowId),now=new Date().toISOString(),mapped=["RUNNING","QUEUED"].includes(index.projection.status)?"PAUSED":index.projection.status,activeRequest=[...index.records].reverse().find(record=>record.kind==="request"&&record.status==="open")?.id??null,activeFailure=index.failure?.id??null,context={...index.context,title:options.issue.title,url:options.issue.url,issueNodeId:options.issue.nodeId,specMarkers:Object.fromEntries(index.specs.map(spec=>[String(spec.version),spec.marker])),latestResults:index.latestResults,continuedFrom:{instance:index.instance,revision:index.projection.revision,publishedAt:index.publishedAt}};
  if(existing)store.db.prepare(`UPDATE work_items SET issue_number=?,issue_id=?,repo=?,branch=?,base_branch=?,updated_at=?,context=?,stage=?,status=?,attempt=?,revision=?,presentation_revision=?,published_presentation_revision=NULL,active_run_id=NULL,active_request_id=?,active_failure_id=?,correction_cycles=?,archived_at=NULL WHERE id=?`).run(index.issue.number,index.issue.id,index.repository.fullName,index.branch,index.base,now,JSON.stringify(context),index.projection.stage,mapped,index.projection.attempt,index.projection.revision,index.projection.revision,activeRequest,activeFailure,index.projection.correctionCycles,index.workflowId);
  else store.db.prepare(`INSERT INTO work_items(id,issue_number,issue_id,repo,branch,base_branch,created_at,updated_at,context,stage,status,attempt,revision,presentation_revision,published_presentation_revision,active_run_id,active_request_id,active_failure_id,correction_cycles) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,NULL,NULL,?,?,?)`).run(index.workflowId,index.issue.number,index.issue.id,index.repository.fullName,index.branch,index.base,now,now,JSON.stringify(context),index.projection.stage,mapped,index.projection.attempt,index.projection.revision,index.projection.revision,activeRequest,activeFailure,index.projection.correctionCycles);
  store.db.prepare("DELETE FROM failures WHERE work_item_id=?").run(index.workflowId);store.db.prepare("DELETE FROM records WHERE work_item_id=?").run(index.workflowId);store.db.prepare("DELETE FROM specs WHERE work_item_id=?").run(index.workflowId);const insertSpec=store.db.prepare("INSERT INTO specs(work_item_id,version,body,criteria,assessment,approved_by,approval_comment_id,approved_at) VALUES(?,?,?,?,?,?,?,?)");for(const summary of index.specs){const fact=byVersion.get(summary.version)!;insertSpec.run(index.workflowId,summary.version,fact.body,JSON.stringify(fact.criteria),fact.assessment===null?null:JSON.stringify(fact.assessment),summary.approvedBy,summary.approvalCommentId,summary.approvedAt);}const insertRecord=store.db.prepare(`INSERT INTO records(id,work_item_id,sequence,kind,spec_version,scope,status,applies_to,payload,source_type,source_id,actor,parent_id,superseded_by,resolved_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);for(const record of index.records)insertRecord.run(record.id,index.workflowId,record.sequence,record.kind,record.spec_version,record.scope,record.status,JSON.stringify(record.applies_to),JSON.stringify(record.payload),record.source_type,record.source_id,record.actor,record.parent_id,record.superseded_by,null,record.created_at,record.updated_at);if(index.failure)store.db.prepare("INSERT INTO failures(id,work_item_id,execution_id,class,message,stage,attempt,created_at,resolved_at,resolved_by) VALUES(?,?,NULL,?,?,?,?,?,?,?)").run(index.failure.id,index.workflowId,index.failure.class,index.failure.message,index.failure.stage,index.failure.attempt,index.failure.created_at,index.failure.resolved_at,index.failure.resolved_by);
  const projection=new WorkflowProjections(store).validateCurrent(index.workflowId),reason={code:"continued",summary:`Continued from ${index.instance} at revision ${index.projection.revision}`,instance:index.instance,revision:index.projection.revision,publishedAt:index.publishedAt};store.event("workflow.transition",{schemaVersion:1,type:"workflow.transition",workItemId:index.workflowId,occurredAt:now,actor:{type:"orchestrator",id:"continuation"},source:{},from:null,to:projection,reason,recordIds:index.records.map(record=>record.id),activeRequestId:projection.activeRequestId,activeFailureId:projection.activeFailureId,specVersion:index.specs.at(-1)?.version??0},index.workflowId);return projection;
 }).immediate();
}
